
#+STARTUP: content showstars indent
#+FILETAGS: dnd notes avadra gahdouh
* Just met

** Veesta,
Fire elemental
Fighter
Kamisha


** Kai,
Blue Tiefling
Codename: 
Mikayla


** Caliopi,
Princess high elf
Druid
CodeName: Seacee
Jess


** Nutmeg, Sprigg,
Gnome
Ranger
Codename: Tigg
Cody


** Jaighosa
Giant
Barbarian
Codename: Trent
Jai


* Fight at the over turned wagon
We found crystals in the back and they are blasphemy crystals. The scales look
to be able to cleanse the crystals.

/Entered on/ [2023-01-28 Sat 19:02]

* Session - l2/17/2023
Sleeping in the tree as we are awoken by caliopi about a swarm descending upon
us. Sephira (the elf that we had rescued) was awoken by caliopi as well. Caliopi
said the swarm was comprised of 6250 flying beings are in the sky carrying bags
of gold (In a British accent). Saphire was really excited to help the group out
with his inventions. The party

sprigg sets a bunch of arrow traps (coordante of arrows) for when the beasts are
in range! While this happens Jaighosa grabs some rocks while caliopi enchants
the rocks to a glowing fury. Veesta sitting in back slowing draws her long bow
back, prepared for murder. Waves of malice reverberate off of Kai. Saphire
was able to give jaighosa minor goggles making him look like Riddick.

** BATTLE ENSUES!!!

As the enemy enters range the skies open up and engulf them in lightning by
caliopi. As i whisper into the night let me grant these eyes of sight to
veesta, sprigg, and caliopi. Woooosh as arrows fly from veesta's bow into
the sky. In a torrent of wind the beasts descend. A mighty grunt ensues as
jaighosa heaves rocks at these large draconic inject swarms come closer.
A wretched noise erupted from the insects as they spewed liquid at the party.

Saphire's stones sprang to life absorbing half the damage of the next volley
of vomit has the stones then moved to everyones respective weapons empowering
the next strike of fury! Unfortunately veesta went down. I moved in to stabilize
then worked my way around the animals. Kai started moving at an alarming rate as
if she took cocaine. The ripples of malice sprang forth in a wave of agony
encompassing the insect swarms. The insects stare into our souls as terror
crept into my body. The creature approached me and hit me across the face.
As i was cast to the ground as the life seemly drained out of me till the
words of caliopi reached me giving me strength. As i get back up nutmeg
looks to have changed into a bear and is gnawing on the creatures engulfing
jaighosa. Saphire ran over to veesta and resuscitated her as she came too
with a scream of surprise as she crawls and glows with glowing green light.
From his hip saphire shoots an all encompassing dancing fire upon the enemy.
After taking so much damage the creatures look to retreat as kai reaches out and
seizes the tail of the beasts as she slashes wildly at the main body.
Writhing in agony it falls to the ground. Whistling past an arrow
hits the beasts and embraced in vines that sprouted from the arrow. Caliopi's
eyes became ablaze as a tiny sun forms on the clump as well. I start to pray
to the banished one as i blink out and in next to jaighosa as i spare him from
death. I then creep my way to the back of the enemy! The swarm engulfs caliopi
as she goes down to the ground. A savage growl emits in the night and a figure
leaps into the night as they crash down from the sky scythe in hand with eyes
emitting a purplish hue. Wind, and water from the energy leaps up and spins
around in a tumultuous swirling mass as the sharpening sound of metal rings out
carving through the monsters' now carcass

** After the Fight
Searching around the dead bodies we found an un-natural amount of gold. Upon
seeing this Saphire tosses a rope up to the clouds and then disappears up it.
His head then pops back out of the cloud and invites us up into his pocket
dimension so we can store this small fortune. "Could anyone help me skin
these creatures so i can test something using their hides" said Sapphire.
As the group is shown by sprigg how to properly breakdown these corpses.

We were able to get every hide that was needed for sapphires. As everyone
makes there way up into the pocket dimension. Sapphire appears terrified of
jaighosa after saving jaigohsa from saying with his rock candy. While in
the pocket jaigohosa tries to apologize to sapphire for scaring him as he
just starts unloading on Jaighosa for being so mean to him. He goes on
to say that he has been alone for a very long and doesn't speak to people
often and this if the first time in a long time and it was terrifying
what jaighosa grabbed him. While this was happening a flashback of
wh hen kai was being swarmed it looked as if kai had blue skin and horns while
being constricted by the swarm? Jaighosa left without saying anything.

I went down to bring him back up and had a heart felt conversation of the
horrors of war and that sapphire is not used to the things we have scene
as well as what we have done. He asks if i have a way to communicate with
people secretly and i tell him i have my ways. After we make our way back up
into the pocket dimension.

When we entered the pocket, we are met with a spicy bowl of curry that was
way to much for me to handle. So i looked like a water genasi from all of
the sweat.

(When ever you are hit by a non-magical weapon, reduce the damage by 1d8
which is done before the resistance is applied. +2 acid damage on the first
attack that done of that action. We will have this ability for 4 hours after
this long rest.) 


After this meal with this group we retired and took a long rest.


** The next day
Upon waking from my meditation i climb down from the whole to speak with
the banished on and i notice sapphire jotting down notes

- Notes :: 
  Notes are being taken by sapphire with what looks like a magical whet stone,
  some brass knuckles, some dragon eggs where it has a question of ACID? next
  to it. Then there is a sword that looks to be dripping which what i cna only
  explain as acid as well. The next not looks to be a cylindrical tube that
  could be used to propel small objects out of it.

Caliopi tells the group about a vision of the mine that we could take which
would allow us to skip any interactions with external parties.
After exiting the mine we notice unnatural growth of plants. The pattern is
weird of this plant it looks like the plants have moved as we had approached
them. It looks like the plants are trying to form a cage around us.

-  Rooted fury ::
   The plants start to attack us as jaighosa gets vine whipped to the ground.
   Veesta with some quick thinking gets him back in the fight with the
   words of wisdom to heal his hurt ego. I then dash out of the way to get with
   the party as caliopi telepots us through a tree 300 yards away.

After we got out of the tree we were hit by a little quake. Caliopi senses the
mine to the northwest of our current location as we make our way there. Around
the cave the humaniods surrounding it look to be a little mindless with foam
coming from their mouths.

Inside of the mind looks like a recently excavated portion where a much larger
crystal existed and it looks like the crystals that we found in the caravan.
This was conveniently around the time that were were attacked by plants again!?
The group then pulls together using the scales that we still have and we
cleansed. The scythe then absorbs all of the energy from the corrupted
crystal. In the energies absence the crystal cracks and in the middle
of it was an egg, and Kai gained a puppy dragon.
* Vista just spoiled
Flame Kelma was the name she whispered to the bartender. The smith that we left
sapphire with seems to be her father!!!!!!!
/Entered on/ [2023-04-14 Fri 21:26]
* The fight club in celesteel is known as bicarbonate
/Entered on/ [2023-05-06 Sat 14:29]
* IG, TG *possble warning, OG, FG passed and FG deteriorated later than the rest but they had to chain it up.
/Entered on/ [2023-05-06 Sat 17:45]
* Fight night
I found against a guy named roid rage. I ended up making him look really silly
with our fight. I hit him with 2 knee kicks and then roid right hooked me so i
had to discombobulate him with a ear clap and a knee to the chin.

Found out we are making our way to spring in order to see a clairvoyant that is
related to sapphire.

There is a sect of magic users named the green wizard society and they look down
on non-magic user. The queen named endu ellen started letting in non-magical
users into spring due to the war!
/Entered on/ [2023-08-26 Sat 19:59]
* On our way to spring to see the clairvoyant
We met a merchant that was selling things that he "found". There was a hammer in
there and Jai freaked out on the shop owner and went running off after he scared
the shop owner. We find a health pot, a +1 bow, and a +1 sword.

After that we teleport, focused on Jai's position and we arrive to see a group
of guards surrounding him.

/Entered on/ [2023-08-26 Sat 22:39]
* The fight!!
Caliopi changed back from an owl and yelled im the princess and the guards started
attacking her instead since she was under arrest!

As avadra emerges from the darkess of the river he says "Darkness rise and touch
the skys, hide Jaigoasa in your guise" as i cast darkness on Jai and teleport
behind a guard.

As the battle ensues caliopi is knocked out of the fight and is taken away by a
guard who teleported out of the battle.

From there we start to disassemble the guards that were left behind. All that is
left now is the mage.

From the side an inhuman being came over and knocked me out as i came too i
tried to find the person i knocked out had been killed so i rummaged around to
find the orders they were given

The orders state the increase because of the war has spilled out of the barrens
and is currently at cold shore and oceana and it is reaching spring.. the orders
have come from a town closer to the main cities that are closer to the main
towns spring

/Entered on/ [2023-08-26 Sat 22:49]

* After a long rest in the cave after the battle
Caliopi uses some spell called transfer via plant so we can go to the ruined
village...caliopi, jai, and kai face planted in mud when they got out.

At the village, there is deathly quite in the air.. piles of corpses and some
dead goliaths laying around the ruins. Most of the weapons are normal farming
tools. The goliaths on the ground are known as the sun graspers being send by
jaigozas dad or a subsect of the tribe that split. They were not supposed to
be in the war anymore. Jai goes into further explanation on what the runes
mean.

Undead goliaths erupt from the rumble as they reach out to attack. They miss
there initial attacks on me as im able to step of the wind away to get the
rest of the party leaving vista behind to fend for herself. 

After getting the party we were able to defeat the corpses as gnomish
directions were yelled to head to a gnomish village. After we buried the
dead bodies of the village we headed that way. Upon getting to the entrance
we seem to be getting arrested. I have to sign to sprigg if she wants me to
swing on them. Sprigg said no so i stopped jaigoza from swinging on the
gnomes. From there sprigg and caliopy were taken prisoner.. sprigg still didn't
want us to start swinging so i went to go get Jai and I tea.

* Back to the action in spring while defending the great tree
In the great tree there were waves of enemies that were defeated and from the smoke
a dragon flies out and uses a breath weapon. I am able to dodge it cause im a boss
From there it flies away and i teleport onto it. However i miss judged the spot.
Robots erupted from the back of it as a ton of robots land on the battle field
It attacks the party some more. I beat the pants off of 2 of the robots and
pummel them into the ground. The dragon then drops a giant mechanical scorpion
on top of me like why is it trying to make me more mad.



- Flint Gatsburg (Scientist)
  He makes cutting edge robot that gives it abilities that normal people couldn't
  make. Ex it utilizes true sight so it can see me. Creating something with true
  sight is very difficult. The sight of the robots is limited in comparison to
  the dragon.

  He is a part of the collective.

- Fern - Spriggs cousin
  Bard
  
* Next session on my birthday
Cold, Fire, Lightning. These can be used as a bomb or a spell casting focus

Half if successful
12d10 if they fail

Handed the capsule of fire to Vesta, calp received the lightning capsule, and
we took the cold capsule.

Sprigg = Spriggtuna

we are talking to Sprigg's cousin.talking about how calp signed documents that started the war.
the documents also say that spring owns spriggs village.

** Dungeon John whats us to explore
On the wall of the entrance there are 6 eyes of the dragon and i know this to be from -
Deepwalkers, cult, base, time of the culling, secret entrances and a false entrance.

Infernow - Dragon of chao

When i was doing a ritual for detect magic Infernow spoke to me and told me i stank
of the raven queen (queen of the dead) and that she had no claim on this realm.

* The Crystal from the dungeon
The other party members that have weapons were blown back from the crystal and
saw visions form it. Calyapy was discribing hers as a tree of sorts and i was
able to sort of describe it as the interwoven tree from the capitol of oceana.
While breaking the rock crystal sprigg was wiping the dust up and got high AF.

We still haven't seen saphire or flare so we sent them a message to see what
was going on. They said they were held up and we thought this was suspicious.
They say they are held up in Ver Instumentious. We tell them we will be there in
3 days and begin out way back to the tree to give. As we head back, jaigosa gets
high AF as well trying to crush a crystal. Now he is wrecking havok on the
surroundings. I just go to get tea. After it was all said and done we go to
revive kai and trixie. Jai, Kai and Vista isn't able to stay in the tree after
all of the destruction. So we go to sleep as they go off.

After getting tea for the 3 in the tree sprigg comes running in saying the others
are possibly in danger. so we run off to go see. As we approach a collapsed cave
Jaigosa looks to be apologizing for being controlled by a kymara and Kai looking
more sinister and standing at the entrance of the cave. I lean over to save
vista from death.

We make our way to instrumentious the city and get through the guard gate using
my war documentation. As we are walking into town we see a poster about an
invention convention from the second most popular family in spring. While doing
that kids who look suspicious approach and offer us tickets, i immediate toss
them a gold and walk away. Jaigosa however tosses one of the kids against a wall
as they try to pick pocket him. They then proceeded to call the guards so Jai
was arrested. Only to be freed by Kai and Caliapi. Veesta, sprigg, and i made
our way to mediocrious (a burrow of the town). We see the green mages murder
someone for made up crimes by lighting them on fire. From there we moved on
to talk with the black smiths about flare and his where abouts.


Caliopi talks with the chancellor dellun Basheik about crippling the green mages,
to gain access to the cystaline show and tell of new stuff. We need to go to
hell to rescue caliopies father and we need to do something to mortal mortal. 

* Next session - Figuring out how to get into the symposium
we follow sprigg into the things and stuff for everything shop where she
purchases an electric tea kettle for all the tea she makes me. Next we move
on to a shop called TBD, pretty sure it means two big dumpies but i digress.
Veesta is looking for a cloak of protection and a ring of protection. Jaigosa
and caliopi go out and find us lodging while in the city inside of musica.
So we headed to veeta in order to buy custom tea cups. Mine was a intricate.
It had light and darkness patterns with the moon and the sun. The cup was
made that morning by star the tea shop elf lady. (Aaron tries to get a
love interested started but avadra is too scarred from the war.) The tea shops
name is called bags. We notice guards fast approaching out location and out of
no where vines appear on the inside of the shop.. as we feel a domain
expansion happens and nothing appears to be inside of the shop.

aza sister to kai and midnight the dog
