#+STARTUP: content showstars indent
#+FILETAGS: dnd notes avadra gahdouh
* Just met Veesta, Kai, Caliopi, Nutmeg, Sprigg, Jaighosa
* Fight at the over turned wagon
We found crystals in the back and they are blasphemy crystals. The scales look
to be able to cleanse the crystals.

/Entered on/ [2023-01-28 Sat 19:02]

* Session - l2/17/2023
Sleeping in the tree as we are awoken by caliopi about a swarm descending upon
us. Sephira (the elf that we had rescued) was awoken by caliopi as well. Caliopi
said the swarm was comprised of 6250 flying beings are in the sky carrying bags
of gold (In a British accent). Saphire was really excited to help the group out
with his inventions. The party

sprigg sets a bunch of arrow traps (coordante of arrows) for when the beasts are
in range! While this happens Jaighosa grabs some rocks while caliopi enchants
the rocks to a glowing fury. Veesta sitting in back slowing draws her long bow
back, prepared for murder. Waves of malice reverberate off of Kai. Saphire
was able to give jaighosa minor goggles making him look like Riddick.

** BATTLE ENSUES!!!

As the enemy enters range the skies open up and engulf them in lightning by
caliopi. As i whisper into the night let me grant these eyes of sight to
veesta, sprigg, and caliopi. Woooosh as arrows fly from veesta's bow into
the sky. In a torrent of wind the beasts descend. A mighty grunt ensues as
jaighosa heaves rocks at these large draconic inject swarms come closer.
A wretched noise erupted from the insects as they spewed liquid at the party.

Saphire's stones sprang to life absorbing half the damage of the next volley
of vomit has the stones then moved to everyones respective weapons empowering
the next strike of fury! Unfortunately veesta went down. I moved in to stabilize
then worked my way around the animals. Kai started moving at an alarming rate as
if she took cocaine. The ripples of malice sprang forth in a wave of agony
encompassing the insect swarms. The insects stare into our souls as terror
crept into my body. The creature approached me and hit me across the face.
As i was cast to the ground as the life seemly drained out of me till the
words of caliopi reached me giving me strength. As i get back up nutmeg
looks to have changed into a bear and is gnawing on the creatures engulfing
jaighosa. Saphire ran over to veesta and resuscitated her as she came too
with a scream of surprise as she crawls and glows with glowing green light.
From his hip saphire shoots an all encompassing dancing fire upon the enemy.
After taking so much damage the creatures look to retreat as kai reaches out and
seizes the tail of the beasts as she slashes wildly at the main body.
Writhing in agony it falls to the ground. Whistling past an arrow
hits the beasts and embraced in vines that sprouted from the arrow. Caliopi's
eyes became ablaze as a tiny sun forms on the clump as well. I start to pray
to the banished one as i blink out and in next to jaighosa as i spare him from
death. I then creep my way to the back of the enemy! The swarm engulfs caliopi
as she goes down to the ground. A savage growl emits in the night and a figure
leaps into the night as they crash down from the sky scythe in hand with eyes
emitting a purplish hue. Wind, and water from the energy leaps up and spins
around in a tumultuous swirling mass as the sharpening sound of metal rings out
carving through the monsters' now carcass

** After the Fight
Searching around the dead bodies we found an un-natural amount of gold. Upon
seeing this Saphire tosses a rope up to the clouds and then disappears up it.
His head then pops back out of the cloud and invites us up into his pocket
dimension so we can store this small fortune. "Could anyone help me skin
these creatures so i can test something using their hides" said Sapphire.
As the group is shown by sprigg how to properly breakdown these corpses.

We were able to get every hide that was needed for sapphires. As everyone
makes there way up into the pocket dimension. Sapphire appears terrified of
jaighosa after saving jaigohsa from saying with his rock candy. While in
the pocket jaigohosa tries to apologize to sapphire for scaring him as he
just starts unloading on Jaighosa for being so mean to him. He goes on
to say that he has been alone for a very long and doesn't speak to people
often and this if the first time in a long time and it was terrifying
what jaighosa grabbed him. While this was happening a flashback of
wh hen kai was being swarmed it looked as if kai had blue skin and horns while
being constricted by the swarm? Jaighosa left without saying anything.

I went down to bring him back up and had a heart felt conversation of the
horrors of war and that sapphire is not used to the things we have scene
as well as what we have done. He asks if i have a way to communicate with
people secretly and i tell him i have my ways. After we make our way back up
into the pocket dimension.

When we entered the pocket, we are met with a spicy bowl of curry that was
way to much for me to handle. So i looked like a water genasi from all of
the sweat.

(When ever you are hit by a non-magical weapon, reduce the damage by 1d8
which is done before the resistance is applied. +2 acid damage on the first
attack that done of that action. We will have this ability for 4 hours after
this long rest.) 


After this meal with this group we retired and took a long rest.


** The next day
Upon waking from my meditation i climb down from the whole to speak with
the banished on and i notice sapphire jotting down notes

- Notes :: 
  Notes are being taken by sapphire with what looks like a magical whet stone,
  some brass knuckles, some dragon eggs where it has a question of ACID? next
  to it. Then there is a sword that looks to be dripping which what i cna only
  explain as acid as well. The next not looks to be a cylindrical tube that
  could be used to propel small objects out of it.

Caliopi tells the group about a vision of the mine that we could take which
would allow us to skip any interactions with external parties.
After exiting the mine we notice unnatural growth of plants. The pattern is
weird of this plant it looks like the plants have moved as we had approached
them. It looks like the plants are trying to form a cage around us.

-  Rooted fury ::
   The plants start to attack us as jaighosa gets vine whipped to the ground.
   Veesta with some quick thinking gets him back in the fight with the
   words of wisdom to heal his hurt ego. I then dash out of the way to get with
   the party as caliopi telepots us through a tree 300 yards away.

After we got out of the tree we were hit by a little quake. Caliopi senses the
mine to the northwest of our current location as we make our way there. Around
the cave the humaniods surrounding it look to be a little mindless with foam
coming from their mouths.

Inside of the mind looks like a recently excavated portion where a much larger
crystal existed and it looks like the crystals that we found in the caravan.
This was conveniently around the time that were were attacked by plants again!?
The group then pulls together using the scales that we still have and we
cleansed. The scythe then absorbs all of the energy from the corrupted
crystal. In the energies absence the crystal cracks and in the middle
of it was an egg, and Kai gained a puppy dragon.
