#+TILE: Dr Indi Jones - Spells

* Default Prepared
** Cantrips
*** Mage Hand
**** Requirements
    Casting Time: 1 action
    Range: 30 feet
    Components: V, S
    Duration: 1 minute
    
**** Description
    A spectral, floating hand appears at a point you choose within range.
    The hand lasts for the duration or until you dismiss it as an action.
    The hand vanishes if it is ever more than 30 feet away from you or if you cast this spell again.
    
    You can use your action to control the hand. You can use the hand to manipulate an object,
    open an unlocked door or container, stow or retrieve an item from an open container,
    or pour the contents out of a vial. You can move the hand up to 30 feet each time you use it.
    
    The hand can’t attack, activate magical items, or carry more than 10 pounds.
 
*** Mend
**** Requirements
    Casting Time: 1 minute
    Range: Touch
    Components: V, S, M (two lodestones)
    Duration: Instantaneous

**** Description    
    This spell repairs a single break or tear in an object you touch,
    such as a broken chain link, two halves of a broken key, a torn cloak, or a leaking wineskin.
    As long as the break or tear is no larger than 1 foot in any dimension, you mend it,
    leaving no trace of the former damage.

    This spell can physically repair a magic item or construct, but the spell can’t restore magic to such an object.
** Level 1 (3/3)

| lvl | Battle Smith Spells               |
|-----+-----------------------------------|
|   3 | Heroism, Shield                   |
|   5 | Branding Smite, Warding Bond      |
|   9 | Aura of Vitality, Conjure Barrage |
