#+TILE: Dr Indi Jones - Spells

* Default Prepared
** Cantrips
*** Mage Hand
**** Requirements
    Casting Time: 1 action
    Range: 30 feet
    Components: V, S
    Duration: 1 minute
    
**** Description
    A spectral, floating hand appears at a point you choose within range.
    The hand lasts for the duration or until you dismiss it as an action.
    The hand vanishes if it is ever more than 30 feet away from you or if you cast this spell again.
    
    You can use your action to control the hand. You can use the hand to manipulate an object,
    open an unlocked door or container, stow or retrieve an item from an open container,
    or pour the contents out of a vial. You can move the hand up to 30 feet each time you use it.
    
    The hand can’t attack, activate magical items, or carry more than 10 pounds.
 
*** Mend
**** Requirements
    Casting Time: 1 minute
    Range: Touch
    Components: V, S, M (two lodestones)
    Duration: Instantaneous

**** Description    
    This spell repairs a single break or tear in an object you touch,
    such as a broken chain link, two halves of a broken key, a torn cloak, or a leaking wineskin.
    As long as the break or tear is no larger than 1 foot in any dimension, you mend it,
    leaving no trace of the former damage.

    This spell can physically repair a magic item or construct, but the spell can’t restore magic to such an object.

** Infusions
*** Enhanced Defense
    Item: A suit of armor or a shield

    A creature gains a +1 bonus to Armor Class while wearing (armor) or wielding (shield) the infused item.

    The bonus increases to +2 when you reach 10th level in this class.

*** Enhanced Weapon
    Item: A simple or martial weapon

    This magic weapon grants a +1 bonus to attack and damage rolls made with it.

    The bonus increases to +2 when you reach 10th level in this class.
   
***   Repeating Shot
    Item: A simple or martial weapon with the ammunition property (requires attunement)

    This magic weapon grants a + 1 bonus to attack and damage rolls made with it when it's used to make a ranged attack, and it ignores the loading property if it has it.

    If you load no ammunition in the weapon, it produces its own, automatically creating one piece of magic ammunition when you make a ranged attack with it. The ammunition created by the weapon vanishes the instant after it hits or misses a target.

** Level 1 (4/4)
*** Cure Wounds
    Casting Time: 1 action
    Range: Touch
    Components: V, S
    Duration: Instantaneous
    
    A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.
    
    At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d8 for each slot level above 1st.

*** Disguise Self
    Casting Time: 1 action
    Range: Self
    Components: V, S
    Duration: 1 hour
    
    You make yourself – including your clothing, armor, weapons, and other belongings on your person –
    look different until the spell ends or until you use your action to dismiss it.
    You can seem 1 foot shorter or taller and can appear thin, fat, or in between. You can’t change your body type,
    so you must adopt a form that has the same basic arrangement of limbs. Otherwise, the extent of the illusion is up to you.

    The changes wrought by this spell fail to hold up to physical inspection. For example,
    if you use this spell to add a hat to your outfit, objects pass through the hat, and
    anyone who touches it would feel nothing or would feel your head and hair.
    If you use this spell to appear thinner than you are, the hand of someone who reaches out
    to touch you would bump into you while it was seemingly still in midair. To discern that
    you are disguised, a creature can use its action to inspect your appearance and must
    succeed on an Intelligence (Investigation) check against your spell save DC.

*** Feather Fall
    Casting Time: 1 reaction, which you take when you or a creature within 60 feet of you falls
    Range: 60 feet
    Components: V, M (a small feather or piece of down)
    Duration: 1 minute
    
    Choose up to five falling creatures within range. A falling creature’s rate of descent slows to 60
    feet per round until the spell ends. If the creature lands before the spell ends, it takes no falling
    damage and can land on its feet, and the spell ends for that creature.
    
*** Faerie Fire
    Casting Time: 1 action
    Range: 60 feet
    Components: V
    Duration: Concentration, up to 1 minute
    
    Each object in a 20-foot cube within range is outlined in blue, green, or violet light (your choice).
    
    Any creature in the area when the spell is cast is also outlined in light if it fails a Dexterity saving throw.
    For the duration, objects and affected creatures shed dim light in a 10-foot radius.
    
    Any attack roll against an affected creature or object has advantage if the attacker can see it, and the
    affected creature or object can’t benefit from being invisible.
** Level 2 (2/2)
*** Blur
    Casting Time: 1 action
    Range: Self
    Components: V
    Duration: Concentration, up to 1 minute

    Your body becomes blurred, shifting and wavering to all who can see you. For the duration,
    any creature has disadvantage on attack rolls against you. An attacker is immune to this effect
    if it doesn't rely on sight, as with blindsight, or can see through illusions, as with true sight.

*** Heat Metal
    Casting Time: 1 action
    Range: 60 feet
    Components: V, S, M (a piece of iron and a flame)
    Duration: Concentration, up to 1 minute
    
    Choose a manufactured metal object, such as a metal weapon or a suit of heavy or medium metal armor,
    that you can see within range. You cause the object to glow red-hot. Any creature in physical contact
    with the object takes 2d8 fire damage when you cast the spell. Until the spell ends, you can use a
    bonus action on each of your subsequent turns to cause this damage again.

    If a creature is holding or wearing the object and takes the damage from it, the creature must succeed
    on a Constitution saving throw or drop the object if it can. If it doesn’t drop the object,
    it has disadvantage on attack rolls and ability checks until the start of your next turn.

    At Higher Levels. When you cast this spell using a spell slot of 3rd level or higher, the damage
    increases by 1d8 for each slot level above 2nd.

* Artificer Spells
| lvl | Battle Smith Spells               |
|-----+-----------------------------------|
|   3 | Heroism, Shield                   |
|   5 | Branding Smite, Warding Bond      |
|   9 | Aura of Vitality, Conjure Barrage |
