#+TILE: Baddah Boom - Spells

* Default Prepared
** Cantrips
   - Thorn Whip ::
     - Casting Time: 1 action
     - Range: 30 feet
     - Components: V, S, M (the stem of a plant with thorns)
     - Duration: Instantaneous
       
     You create a long, vine-like whip covered in thorns that lashes out at your command toward a creature in range.
     Make a melee spell attack against the target. If the attack hits, the creature takes 1d6 piercing damage, and if
     the creature is Large or smaller, you pull the creature up to 10 feet closer to you.

     - At Higher Levels ::
       This spell’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).
     
   - Fire Bolt ::
     - Casting Time: 1 action
     - Range: 120 feet
     - Components: V, S
     - Duration: Instantaneous

     You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a
     hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn’t being worn or
     carried.

     This spell’s damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).
 
** Level 1 (3/3)
   - Cure Wounds ::
     - Casting Time: 1 action
     - Range: Touch
     - Components: V, S
     - Duration: Instantaneous

     A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier. This spell
     has no effect on undead or constructs.

     - At Higher Levels ::
       When you cast this spell using a spell slot of 2nd level or higher, the Healing increases by 1d8 for each slot
       level above 1st.
    
   - Faerie Fire ::
     - Casting Time: 1 action
     - Range: 60 feet
     - Components: V
     - Duration: Concentration, Up to 1 minute

     Each object in a 20-foot cube within range is outlined in blue, green, or violet light (your choice). Any creature
     in the area when the spell is cast is also outlined in light if it fails a Dexterity saving throw. For the
     duration, objects and affected creatures shed dim light in a 10-foot radius.

     Any attack roll against an affected creature or object has advantage if the attacker can see it, and the affected
     creature or object can’t benefit from being invisible.

   - Feather Fall ::
     - Casting Time: 1 reaction
     - Range: 60 feet
     - Target: Up to five falling creatures within range
     - Components: V M (A small feather or piece of down)
     - Duration: 1 minute

     Choose up to five falling creatures within range. A falling creature’s rate of descent slows to 60 feet per round
     until the spell ends. If the creature lands before the spell ends, it takes no falling damage and can land on its
     feet, and the spell ends for that creature.

   - Tasha's Caustic Brew ::
     - Casting Time: 1 action
     - Range: Self (30-foot line)
     - Components: V, S, M (a bit of rotten food)
     - Duration: Concentration, Up to 1 minute

     A stream of acid emanates from you in a line 30 feet long and 5 feet wide in a direction you choose. Each creature
     in the line must succeed on a Dexterity saving throw or be covered in acid for the spell’s duration or until a
     creature uses its action to scrape or wash the acid off itself or another creature. A creature covered in the acid
     takes 2d4 acid damage at start of each of its turns.

     - At Higher Levels ::
       When you cast this spell using a spell slot 2nd level or higher, the damage increases by 2d4 for each slot level
       above 1st.

   - Magic Missle ::
     - Casting Time: 1 action
     - Range: 120 feet
     - Target: A creature of your choice that you can see with range
     - Components: V, S
     - Duration: Instantaneous

     You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within
     range. A dart deals 1d4 + 1 force damage to its target. The darts all strike simultaneously, and you can direct
     them to hit one creature or several.

     - At Higher Levels ::
       When you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot
       above 1st.

   - Thunder Wave ::
     - Casting Time: 1 action
     - Range: Self (15-foot cube)
     - Target: Self (15-foot cube)
     - Components: V, S
     - Duration: Instantaneous

     A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a
     Constitution saving throw. On a failed save, a creature takes 2d8 thunder damage and is pushed 10 feet away from
     you. On a successful save, the creature takes half as much damage and isn’t pushed. In addition, unsecured objects
     that are completely within the area of effect are automatically pushed 10 feet away from you by the spell’s effect,
     and the spell emits a thunderous boom audible out to 300 feet.

     - At Higher Levels ::
       When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot
       level above 1st.
