 #+STARTUP: content showstars indent
#+FILETAGS: dnd notes chewy
* Playing with Dasha, rowgar, tregar, Chewy, and owner of cluckenbell 

Just met Lily.
Zyhira darren ambassador to the storm queen.
  Queen cerisa of malestrom (of giants). Giants can't sit by.
  Disappearances of ships. Wants to hire us.
/Entered on/ [2022-02-27 Sun 17:54]
* Ship that were coming or going that ended up missing
Dregar R - carries red spear, the gracefull dancer- farmon mabbot,
Hammer - dornal cast bow, Lesgar maid - larsh vertock, sea queens fury - clara k, Splendor - golden goldtooth olen
/Entered on/ [2022-02-27 Sun 18:06]
* The crew of the pursuit are friends
/Entered on/ [2022-02-27 Sun 18:10]
* Caravel outfitted for speed. Termission sailors. CPT Argowi - Short beard
/Entered on/ [2022-02-27 Sun 18:21]
* The harbor master may know if anyone from the missing ships come back
/Entered on/ [2022-02-27 Sun 18:29]
* Mostiquen Tobacco - most people can't tell the difference.
/Entered on/ [2022-02-27 Sun 18:39]
* At the frayed line - tavern
Alben Grippa is the drunk sailor that was a part of the graceful dancer - Daphlahh the in keep

/Entered on/ [2022-02-27 Sun 19:00]
* Tattooed eastern man
Hired that dancers crew to enslave/maroon sailors and steal cargo. 
/Entered on/ [2022-02-27 Sun 19:17]
* Taking the sailors up to isolation a tiny little island.
/Entered on/ [2022-02-27 Sun 19:19]
* Teiflin ex assistant named wesley who might be a part of gannnnnnnng
/Entered on/ [2022-02-27 Sun 20:32]
* On island, ship will show up 1x5 at midnight
/Entered on/ [2022-03-06 Sun 17:20]
* Found some shelter that will work for us to stay in
/Entered on/ [2022-03-06 Sun 17:33]
* Dunkin that was captured says
maxent is an important figure in the town. Eagleton, cerious ship rights. Quint is his captain.
There are about 70 pirates.
Unknown beast.
Patrolling for the beast.
Warehouse full of cargos and the slaves are close and appraisers office
The volcano there is a bell that rings beginning of day and end of day.
/Entered on/ [2022-03-06 Sun 19:06]


* Portico is on all of the ship departures. Reciepts for bear food from mangockpock.
/Entered on/ [2022-03-06 Sun 20:07]
* Found people outside of cave under volcano where bell cam from
Amri - halflin. Hired to look at the disruption of trade. Hired by a king.
Tua - human
Sourous -teiflin

/Entered on/ [2022-03-06 Sun 20:30]
* The city has lost some people and are trying to recruit people to investigate why people are missing.
Town of vermillion. Gunther is our point of contact.
/Entered on/ [2022-03-13 Sun 17:27]


* 16/60 miners survived a mine collapse. The survivors started to disappear.
/Entered on/ [2022-03-13 Sun 17:36]
* The people that survived never were the same after the incident like they don't have the will to live.
/Entered on/ [2022-03-13 Sun 17:43]
* Guertrude, gregory (son), and george taken. Heading to family farm. This all started happneing in the last week
/Entered on/ [2022-03-13 Sun 17:45]
* Going to want to stop at the Bored weasal (tavern / inn) along the way.
/Entered on/ [2022-03-13 Sun 17:50]
* Lucas used to work in the mine but was retired well before the collapse
/Entered on/ [2022-03-13 Sun 18:07]
* Vermillion is really quite and alot of overgrowth. Overcast.
/Entered on/ [2022-03-13 Sun 18:29]
* Found a shield (50 GP), 2 short swords (25 GP), iron bars (10 gp) in the wand and hammer building
/Entered on/ [2022-03-13 Sun 18:52]
* Found chunk of platinum worth 25 GP in the mayor house
/Entered on/ [2022-03-13 Sun 19:44]
* The melocs that we killed in the mayor building look to be possible villagers that were changed by fear.
/Entered on/ [2022-03-13 Sun 21:00]
* Working on the Deep creeping darkness in the candle keep mysteries
/Entered on/ [2022-03-13 Sun 21:01]


* Starting in a village where there is a well where we need to fine the throne.
Playing with Reign, Regan, seph, Belvis, flick and flitter
/Entered on/ [2022-03-20 Sun 17:38]
* Beyond the 
/Entered on/ [2022-03-20 Sun 17:47]
* South of here in a secret path beyond a 2 headed king look to the left
/Entered on/ [2022-03-27 Sun 19:33]
* Down from 2 headed king
Down the stairs from the 2 headed king down the left hallway there is a goblin market. Down the right hall there is a water spicket.
/Entered on/ [2022-04-03 Sun 20:02]
* Past the water pump room
Past the pinicio room there was a rotten smelling room with this carved in a body
"As many as there are stars in the skies" - This looks to be the base camp for the Xanthar guild

/Entered on/ [2022-04-03 Sun 20:47]
* Entered a copper room with a lighting skull
Killed the skull, threw a piece of skull down the
hole to a multi mouth and eyed monster. Went to explore other room with bad stench. 
/Entered on/ [2022-04-24 Sun 20:25]
* Dropped down the shoot, and fought the multi mouth and eye monster
Belvis killed the monster and cleaned off the alter and was given a boon to see hidden doors
/Entered on/ [2022-04-24 Sun 21:18]
* Belbis and seph out this week, (zack) ACHMINOS joined 
