#+STARTUP: content showstars indent
#+FILETAGS: dnd notes flam
* Players
- Ares ::
  Tiefling
  Bard
  Kamisha
  
- Thesban ::
  Human
  Bard
  Cody
  
- Alar ::
  Elf
  Rogue
  Adrian
  
- Gock ::
  Goliath
  Barbarian
  Tyler
  
- Prof Phillip Rayburn ::
  
  Artificer
  Aaron
  
- Ishtar ::
  Human
  Cleric
  Jai 

- Fayrus ::
  Fairy
  Druid
  Jess

* Note
** Met the party
- Ares tells us about the ghost house she defeated with some sort of mom inside
  Then tells us about the poo monster in the sewers both of which she single
  handedly defeated.

- We are trying to get to Hamlens rest. We have deemed Ares as the leader.

- We are taken to the family quevarah.
  - Andari and Marsela are the mom and dad
  - Nadja, raul, and sonja are the children
  - Papa Niko grandpa
  - tilda and topar are the cousins
  - There are only 2 children with the family and the middle child Nadja is
    missing. Nadja has flaming red hair!

  - We started talking with Sophia about what happened the day her sister was taken
    Nadja was grabbed from behind in the alley and was taken away. From there we
    head to the candy shop that sold the candy wrappers we found in the alley
    way when we investigated.
  - We arrived at Tabby's Taffy
    - Tabaxi named Tabby makes the candy

  - Matilda's Dresses (CLothing Shop)
    They walked past here and didn't go in today
  - Fitzbees Toy shop
    Upon entering we met Fizbee, middle aged dwarf. when asking more questions
    Orla was called from the back. She comes out with a limp on a crutch. We are
    trying to figure out what was purchased yesterday. It turned out to be an
    automaton dragon. As Orla leaves, alar senses that orla was lying about not
    knowing what is going on. So Alar unlocks the door using lock picking. So
    we move down the hall till we approach another locked door with a stair case
    leading down. We enter into a large storage room and we start to investigate
    since we still do not see Orla. Ares single handly moves shelf to
    reveal secret door. Gock kicks down the door. From there we enter what looks
    to be a large unused area. It looks like an area full of discarded toys by
    Fitzbees and in the corner Fitzbee stands with orla who is crying. The group
    begins to question the toy maker. In an instance Fitzbees facial expression
    changes and then dolls start attacking the party.

  - BATTLE
    - From there Alar shot the crippled girl orla in the leg.
    - Fitzbee shoots 3 fire bolts at Ares and misses.
    - Ares was able to hit fitzbee as he ran away.
    - Phisben walks over to a door and there is nothing in there.
    - Ishtar casts scared flame on Fitzbee
    - Anomatronic Bots come out of rooms and start attacking ares and flubber.
    - We cast silvery barbs to save ares from getting hit! Sidenote, Thesbin
      also casted it and then asked who was next and it was aaron then weennnt
      ohhhhh no i give it to Jai.
    - The prof then tells flubber to abduct the crippled injured girl. 

  - The profession is very angry for no reason .. The prof says he was to inject
    his ooze with serums.
    
** BACK to the action
- Arris runs from the silence to escape the automatons while the daughter of the
  toy maker escaped from flubbers grasp. 
- Fayrus runs in from waking up late to see alar is spider manning a shelf as he
  hides from the enemy.
- The professor from there tries to shoot the toy makers daughter, he said "non
  lethally". Good thing his gun jams so he is able to figure it out.
- Alar pops out and critically hits the daughter and knocks here unconscious!
- I had to kick the doll in the face and it stabbed me as i ran away! It really
  hurt. My soul is then taken over by the doll and i'm forced to attack my
  party of people!
- Professor changes his gun into a shock baton and begins attacking the automaton
  but i am forced to cast silvery barbs on him forcing it to miss.. i think
  thesban saw me and now i have to figure out how to explain this.
- The rest of the monsters seem to be falling one after another since Alar is
  slaughtering everything with his bow! I thne begin to run and the professor
  cries out to stop me and alar stabs me.. HE STABS me. As i hear a suggestion
  in my head and i was told to sit down on my hands.. so now i'm just chilling
- The professor walks over to me and slaps me two times and starts asking me
  what color are his underwear why did he ask me that?!
- Fayrus goes over and starts to autopsy the dolls and as he cuts it up Flam
  dies in the middle of the professor slapping me.
- The toy maker manically starts to laugh, and says "HAHA YOU KILLED HIM, WE
  ARE FREE NOW!".. Alar starts interrogating him and the toy says "You can try
  to kill me and these bodies are ours and we are free!"
- The professor opens up a chest and finds a green cloak.
- Alar begins to search and find a hidden room behind a book shelf. There is
  a giant human sized doll that begins to speak saying "We had everything planned
  and you all RUINED IT!!!".. It floats down and a fight starts again.
  Annebell begins to attack with animated chains Alar with razor blades and
  grapples him.. Alar broke out and ran and hid. The chains begin to attack
  ares and slashed at her and grapples her. The professor rushes in and says
  "I cant wait to experiment on you".. annebell replies "I'd like to see you try"
  After that he starts wailing on the doll as he stair in its eyes. Ishtar runs
  in and sacred flames the doll. Fayrous tries to run in and help and is grappled
  by a chain as he leaves its range. Annebell uses her strings to move out of range
  then commands the string to do slashing to ares. Then she looks at weebo and
  slices weebo in half. As the professor shocks annebell with his baton
  it says "Haha that tickled.. IMMA MAKE YOU TICKLED ON THE INSIDE!!" Feyrous and
  ares are pulled into the ceiling hard and are grappled and dropped from the
  ceiling.     
    
* AWAKENING
In a wakeless dream i am in the middle of cross roads unable to get out of the
middle of the road. A messenger rides a bike down the road and hands me a letter.
The wax insignia is a black raven skull like insignia. I am unable to read it
but i understand what it says and i make some sort of deal to come back to life.
I awaken in a temple as someone was about to cut me open! Flim and myself join
the party and we continue down the road in a caravan with the group.

Out of no where a headless horseman rides after us and wants to take theisben;s
head from him. As we run away and the rider disappears as we cross the bridge
and we are safe. We find out someone calls it an aduala.

We have made it to hamlen's rest, apparently it is a town..

Goran Stonebelly is the blacksmith of the town, muffin starts flirting with him
and its kinda weird to watch this exchange.

We are now following thesban into the spell shop and flim asks for a potion of
slipperiness and the expert said no but we have an oil of it. Thesban hand over
the scroll of bestow curse to the shop owner and gets store credit. He gets
to jugs of alchemy, 2 health potions.. it seems like he only cares about himself
and glue.

So we met hamlen who was the owner of the in when he was alive. He mentioned
that the raven skull we have means we should talk with the grave mother.
Alar asks a question about strad and then Hamlen says LORD STR...Lord of
burovia.
