#+STARTUP: content showstars indent
#+FILETAGS: dnd notes flam
* Players
- Ares ::
  Tiefling
  Bard
  Kamisha
  
- Thesban ::
  Human
  Bard
  Cody
  
- Alar ::
  Elf
  Rogue
  Adrian
  
- Gock ::
  Goliath
  Barbarian
  Tyler
  
- Prof Phillip Rayburn ::
  
  Artificer
  Aaron
  
- Ishtar ::
  Human
  Cleric
  Jai

* Note
** Met the party
- Ares tells us about the ghost house she defeated with some sort of mom inside
  Then tells us about the poo monster in the sewers both of which she single
  handedly defeated.

- We are trying to get to Hamlens rest. We have deemed Ares as the leader.

- We are taken to the family quevarah.
  - Andari and Marsela are the mom and dad
  - Nadja, raul, and sonja are the children
  - Papa Niko grandpa
  - tilda and topar are the cousins
  - There are only 2 children with the family and the middle child Nadja is
    missing. Nadja has flaming red hair!

  - We started talking with Sophia about what happened the day her sister was taken
    Nadja was grabbed from behind in the alley and was taken away. From there we
    head to the candy shop that sold the candy wrappers we found in the alley
    way when we investigated.
  - We arrived at Tabby's Taffy
    - Tabaxi named Tabby makes the candy

  - Matilda's Dresses (CLothing Shop)
    They walked past here and didn't go in today
  - Fitzbees Toy shop
    Upon entering we met Fizbee, middle aged dwarf. when asking more questions
    Orla was called from the back. She comes out with a limp on a crutch. We are
    trying to figure out what was purchased yesterday. It turned out to be an
    automaton dragon. As Orla leaves, alar senses that orla was lying about not
    knowing what is going on. So Alar unlocks the door using lock picking. So
    we move down the hall till we approach another locked door with a stair case
    leading down. We enter into a large storage room and we start to investigate
    since we still do not see Orla. Ares single handly moves shelf to
    reveal secret door. Gock kicks down the door. From there we enter what looks
    to be a large unused area. It looks like an area full of discarded toys by
    Fitzbees and in the corner Fitzbee stands with orla who is crying. The group
    begins to question the toy maker. In an instance Fitzbees facial expression
    changes and then dolls start attacking the party.

  - BATTLE
    - From there Alar shot the crippled girl orla in the leg.
    - Fitzbee shoots 3 fire bolts at Ares and misses.
    - Ares was able to hit fitzbee as he ran away.
    - Phisben walks over to a door and there is nothing in there.
    - Ishtar casts scared flame on Fitzbee
    - Anomatronic Bots come out of rooms and start attacking ares and flubber.
    - We cast silvery barbs to save ares from getting hit! Sidenote, Thesbin
      also casted it and then asked who was next and it was aaron then weennnt
      ohhhhh no i give it to Jai.
    - The prof then tells flubber to abduct the crippled injured girl. 

  - The profession is very angry for no reason .. The prof says he was to inject
    his ooze with serums.
