#+STARTUP: content showstars indent
#+FILETAGS: dnd notes bo grimspine




* Notes from session
** Gibbering Mouth Room
Stillben, Vivv, Trinket, Bastion, and myself were in a room were gibbering
mouths dropped from the ceiling. Three of them came down and we handled them
fairly quickly. I just got blinded by goop and just healed myself. (If it
matters bastion got two kills and stillben only got one).

When we first entered the room, Bastion had ran to the other end fighting a
gibbering mouth by himself. He made fairly quick work of it considering it
seemed to be tougher than the others. After The one at the end was dead, he came
to help with the middle one. Vivv, Bastion, and Stillben were all attacking it.

Meanwhile there was one that dropped near the entrance and was next to tinker
and I. Tinker deployed some flame thrower turret and seemed to be dealing with
it alright. The gibbering mouth shot some sort of goop in my eyes and I lost
vision for the remainder of the fight.

Once the middle one was defeated, Stillben ran along the wall to aide tinker in
defeating the one that dropped in by the door.

We then went to go look for the others. I used thaumaturgy to try to call out
but there was no response.

We found a weird skull wall thing and eventually were able to pass through due
to trinket touching it or something. After that venture through the wall we
came to a room where the others were laying unconscious and shaking. Stillben
smacked them each with a stick and they woke up.

We then took a short rest on the steps that descend further into the tower.

** Flameskull Room
While the gibbering mouth fight was happening, Illiana, Suriah, Jag, and Zamaan
were in a shared fever dream of some sort fighting three green flameskulls. They
got in a couple good shots but not enough.

One flameskull downed zamaan with a fireball. Then next somehow exploded while
trying to do the same. the third however, was able to down the rest of the party
with the help from the first one on its next turn.

** Weird Vase
There is a vase that Illiana, Suriah, and Zamaan threw valuables into. Currently
Stillben has it and is trying to figure it out.

He put in a scroll and the eyes of the scroll vase light up as the scroll
ignited. When he did that I felt something far away f=move via the virations of
the ground. Stillben was weird about the scroll.

Stillben had found that the table the vase was on had risen and revealed a new
hallway. This is where we chose to go next.

** Music Hall
We came into a large room that had four larger braziers. We found a way to light
them (not sure how it triggered). We Heard music that seemed to try to enchant
us so I casted silence on the closest brazier. This reached the entrance and
allowed me to walk in while under the silence bubble.

The flames of the brazier took on humanoid shapes and started dancing. Suriah
danced with one of them and it jumped up and touched a symbol on the glass
above. She did this with another one as well. I dropped silence and cast
guidance on Suriah to have her keep dancing. She did not dance well....The flame
and I were both disappointed. Illian, however, pulled through and was able to
charm the last two.

As the last one jumped into the mosaic, the wall underneath it opened up into a
passageway. The Passageway is a long hallway with black chains on the floor and
carvings of supine figures in chained bodies on the way.

In this room there is this passageway, and a set of double doors. Vivv went down
the passageway and the chains came to life as she fell prone. A voice called out
to lock her away. I cast Dispel Magic and was able to get rid of the effect on
the chains and allowing her to no longer be prone.

At the end of this hallway we found a hole in the ground. Lillian cast Dancing
lights down this dark hole. The Hole looks to go further than what we can see.
Using rope, we found out the hole seems to go down 100ft.

Bastion used a spell and discerned that this hole is a prison that is holding
either a fiend of celestial.


** Black Hole
Trinket sent a humonculus servant down that came back and seemed to gesture that
there was danger down there. Vivv really wanted to go down the hole and was
trying to get us to go down there.

Suriah went down the hole as bird. She was very scared after coming back from
the hole. When she came up she telepathically communicated with Jag and informed
us that there is a statue being chained and hooked with its mouth being hooked
up spreading its lips apart and a pair of double doors in its chest that seemed
to be missing handles. However, the statue appears to be extacy instead of pain.

Stillben was tying rope to go down the hole and tied some around Suriah's leg.
He was planning on trying to discern if she was in danger but didn't think about
it. 

** Doubles Doors
we decided to go through the double doors in the music hall instead of the
demonic death hole. Stillben opened the double doors and found a room filled
with green glowing spider web all over the room. Crawling among those webs were
two driders and two giant spiders.

We tried to close the doors and nope out, but the driders burst through the
doors initiating combat.

The driders cast darkness on the entrance to the room blocking a lot of vision.
I scooted into the darkness to try to find Stillben that went down. I found his
body and waited next to it until i could see him to heal him. I used a bonus
action to shield of faith on myself bring AC to 23.

We had discussed a solution to the darkness and Tinker cast Light on a rock and
then the magical light rock into the center of the darkness circle allowing us
to see normally. 

Because he was unable to see through the darkness, Zumaan ran forward by himself
into the room so that he could try to get a shot. Vivv turned into a wolf and
ran after him on her turn.

After healing stillben back up, I witnessed a drider swing down and execute
Zumaan. Upon seeing this, I sprinted in and cast revivify bring zumaan back to
life. This consumed the diamond that was bought for you. After that, Vivv ran
out carrying Zumaan to saftety as the rest of us stayed to fight.

After being healed, Stillben started to fight one of the giant spiders was able
to bring it down. Similarly, Illian was fighting a giant spider as well and was
also able to slay it.

During this whole thing, I believe that Suriah was losing her mind due to the
demon hole she went down.

Bastion had stepped up to fight the first Drider and was able to deal a lot of
damage via attacks and smite to finish it off. Vivv was in wolf form and was
attacking the Drider that was fighting Zumaan. 

During this time, Trinket had deployed a force turret and shot the drider. This
pushed the drider back moving him out of my melee range. Then, before I was able
to move again, Bastion and Illiana had moved between the Drider and I. The
Drider then attacked Illiana downing her. I then moved over beside the now dying
Illiana and the attacked the Drider with my warhammer. The blow killed the
monster.

Everyone kept dying because they wouldn't stand behind the person with 23 AC
that happens to have resistance to poison damage.

After the people died, I stepped up and bonked the drider on the head killing it
and then walked out of the room.


** Post combat with Spiders
As I was walking away from the drider I saw something strike Vivv in the back.

Upon walking up the Vivv I found out that Suriah had attacked her. Suriah seems
to be possessed by something from when she went down the hole.

We are keeping Suriah bound and gagged until we can figure out how we can make
her better. After she was bound, I attempted lesser restoration to no effect.
 
