#+STARTUP: content showstars indent
#+FILETAGS: dnd notes bo grimspine
* Sillben, SILVY (viv), trinket, bastion, zamon, jag, illiana, zariah
* Notes from session
** Gibbering Mouth Room
Stillben, Vivv, Trinket, Bastion, and myself were in a room were gibbering
mouths dropped from the ceiling. Three of them came down and we handled them
fairly quickly. I just got blinded by goop and just healed myself. (If it
matters bastion got two kills and stillben only got one).

WHEN WE ENTERED THIS ROOM, STILLBEN FLUNG THE DOORS OPEN BY HIMSELF IN A VERY
COOL WAY. THIS WILL BE HOW ALL DOUBLE DOORS OF THE SESSION WERE OPENED.

When we first entered the room, Bastion had ran to the other end fighting a
gibbering mouth by himself. He made fairly quick work of it considering it
seemed to be tougher than the others. After The one at the end was dead, he came
to help with the middle one. Vivv, Bastion, and Stillben were all attacking it.

Meanwhile there was one that dropped near the entrance and was next to tinker
and I. Tinker deployed some flame thrower turret and seemed to be dealing with
it alright. The gibbering mouth shot some sort of goop in my eyes and I lost
vision for the remainder of the fight.

Once the middle one was defeated, Stillben ran along the wall to aide tinker in
defeating the one that dropped in by the door.

We then went to go look for the others. I used thaumaturgy to try to call out
but there was no response.

We found a weird skull wall thing and eventually were able to pass through due
to trinket touching it or something. After that venture through the wall we
came to a room where the others were laying unconscious and shaking. Stillben
smacked them each with a stick and they woke up.

We then took a short rest on the steps that descend further into the tower.

** Flameskull Room
While the gibbering mouth fight was happening, Illiana, Suriah, Jag, and Zamaan
were in a shared fever dream of some sort fighting three green flameskulls. They
got in a couple good shots but not enough.

One flameskull downed zamaan with a fireball. Then next somehow exploded while
trying to do the same. the third however, was able to down the rest of the party
with the help from the first one on its next turn.

** Weird Vase
There is a vase that Illiana, Suriah, and Zamaan threw valuables into. Currently
Stillben has it and is trying to figure it out.

He put in a scroll and the eyes of the scroll vase light up as the scroll
ignited. When he did that I felt something far away f=move via the virations of
the ground. Stillben was weird about the scroll.

Stillben had found that the table the vase was on had risen and revealed a new
hallway. This is where we chose to go next.

** Music Hall
We came into a large room that had four larger braziers. We found a way to light
them (not sure how it triggered). We Heard music that seemed to try to enchant
us so I casted silence on the closest brazier. This reached the entrance and
allowed me to walk in while under the silence bubble.

The flames of the brazier took on humanoid shapes and started dancing. Suriah
danced with one of them and it jumped up and touched a symbol on the glass
above. She did this with another one as well. I dropped silence and cast
guidance on Suriah to have her keep dancing. She did not dance well....The flame
and I were both disappointed. Illian, however, pulled through and was able to
charm the last two.

As the last one jumped into the mosaic, the wall underneath it opened up into a
passageway. The Passageway is a long hallway with black chains on the floor and
carvings of supine figures in chained bodies on the way.

In this room there is this passageway, and a set of double doors. Vivv went down
the passageway and the chains came to life as she fell prone. A voice called out
to lock her away. I cast Dispel Magic and was able to get rid of the effect on
the chains and allowing her to no longer be prone.

At the end of this hallway we found a hole in the ground. Lillian cast Dancing
lights down this dark hole. The Hole looks to go further than what we can see.
Using rope, we found out the hole seems to go down 100ft.

Bastion used a spell and discerned that this hole is a prison that is holding
either a fiend of celestial.


** Black Hole
Trinket sent a humonculus servant down that came back and seemed to gesture that
there was danger down there. Vivv really wanted to go down the hole and was
trying to get us to go down there.

Suriah went down the hole as bird. She was very scared after coming back from
the hole. When she came up she telepathically communicated with Jag and informed
us that there is a statue being chained and hooked with its mouth being hooked
up spreading its lips apart and a pair of double doors in its chest that seemed
to be missing handles. However, the statue appears to be extacy instead of pain.

Stillben was tying rope to go down the hole and tied some around Suriah's leg.
He was planning on trying to discern if she was in danger but didn't think about
it. 

** Doubles Doors
we decided to go through the double doors in the music hall instead of the
demonic death hole. Stillben opened the double doors and found a room filled
with green glowing spider web all over the room. Crawling among those webs were
two driders and two giant spiders.

We tried to close the doors and nope out, but the driders burst through the
doors initiating combat.

The driders cast darkness on the entrance to the room blocking a lot of vision.
I scooted into the darkness to try to find Stillben that went down. I found his
body and waited next to it until i could see him to heal him. I used a bonus
action to shield of faith on myself bring AC to 23.

We had discussed a solution to the darkness and Tinker cast Light on a rock and
then the magical light rock into the center of the darkness circle allowing us
to see normally. 

Because he was unable to see through the darkness, Zumaan ran forward by himself
into the room so that he could try to get a shot. Vivv turned into a wolf and
ran after him on her turn.

After healing stillben back up, I witnessed a drider swing down and execute
Zumaan. Upon seeing this, I sprinted in and cast revivify bring zumaan back to
life. This consumed the diamond that was bought for you. After that, Vivv ran
out carrying Zumaan to saftety as the rest of us stayed to fight.

After being healed, Stillben started to fight one of the giant spiders was able
to bring it down. Similarly, Illian was fighting a giant spider as well and was
also able to slay it.

During this whole thing, I believe that Suriah was losing her mind due to the
demon hole she went down.

Bastion had stepped up to fight the first Drider and was able to deal a lot of
damage via attacks and smite to finish it off. Vivv was in wolf form and was
attacking the Drider that was fighting Zumaan. 

During this time, Trinket had deployed a force turret and shot the drider. This
pushed the drider back moving him out of my melee range. Then, before I was able
to move again, Bastion and Illiana had moved between the Drider and I. The
Drider then attacked Illiana downing her. I then moved over beside the now dying
Illiana and the attacked the Drider with my warhammer. The blow killed the
monster.

Everyone kept dying because they wouldn't stand behind the person with 23 AC
that happens to have resistance to poison damage.

After the people died, I stepped up and bonked the drider on the head killing it
and then walked out of the room.


** Post combat with Spiders
As I was walking away from the drider I saw something strike Vivv in the back.

Upon walking up the Vivv I found out that Suriah had attacked her. Suriah seems
to be possessed by something from when she went down the hole.

We are keeping Suriah bound and gagged until we can figure out how we can make
her better. After she was bound, I attempted lesser restoration to no effect.
 

* 2023/02/12 - Notes from session 
Came back to the hall with swords and we have a decision to offer up blood to
make the swords go away.

People walk down the hallway to fill a reservoir up with blood, once full then
the door was outlined in blood at the end of the hall way.

Made it to the bottom of the stairs to a large open into a large room with a statue
and a jungle gym. Behind the statue there is a very long hallway. So we have to
climb the loin cloth of the statue to get up to the double doors in the chest of
the statue.

This is the statue that was at the bottom of the hole that zahriah went down.
The statue looks to be enjoying being brought down by pain and suffering. About
40 feet in the air there are interlocking hands meeting at the end of the room.
With the statue in the middle. At the base of each of the arms are glowing orbs.
The orb looked to move up to the palm of the hand and expanding in size.

Stillben walked over to thr right arm and then hit it with his stick and then
punching it as the orb was destroyed with a one inch punch. He let out a shot
telling us to destroy the orbs!! Bastion lets jag know he owes him for not
throwing his ax a second time towards the orb in the air. I walk over to stillben
and he starts to attack me with his stick. As jag hooks a rope aaround the thumb
and then takes the short sword and swings at the orb in a show of splunking
prowess.

As illiana yells move and bo, pissed off from being hit by stillben,
spartan kicks stillben 30 feet across the room as he dives out of the way.
The lightning arrow whizzes in and annihilates the orb. Stillben runs over and
starts hitting me again while prone on the ground. As he comes to from his
fits of rage. Viv attacks and downs zariah as her blades are covered in blood.
She lets out a blood curdling scream as she sees that she is actively killing
her cousin. Bastion then walks over and knocks viv out as his ax glowed with
radiant energy. Bo stands up and shields of faith as he (pissed off) side eyes
stillben. He prays to god to not act out against his friend and lead him from the
valley of darkness. He walks over to the downed party members as he says we
will fucking talk through this later to stillben.

Inside of the door it leads down a hallway which opens up into a large theatre
room filled with crystals that slope down to a crystal alter. Illian yelled to
come in because she got the feeling that it will cleanse the madness that people
are having. Apparently inside of this room stillben slides on his back down to 
the alter and knocks himself out on the alter. Illiana starts trying to do
medicine checks and has no idea what she is looking at. I saved Zariah with
spare the dying and then made my way up as i heard zariah scream that stillben
was down. As i made my way down to the crystal alter i slipped and fell and died

Elixian who i saw in my previous vision. You came you followed you can find me.
The crystals start to shine around us. The vision pops in of soldiers surrounding
Elxian as they are headed off on a mission. It fades into a battle of him
surrounded be dead bodies of his comrades as he fights demons around him.
He is thrown by a demon and put on his knees. The vision shifted into him
in his underwear and him asking for help. I ask "Where can i save you from?"

He replies "The underwater city of Caelmarrow." he is surrounded in darkness and
it seems like torture.

The vision fades.

Bastion ties a health potion to a rope and sends it down to illiana to give to
stillben. He sits on the alter and nothing happens and then stillben puts me
on the alter and nothing happens as we use a rope to get everyone up from the
alter. We get everyone up into the statue and then zariah and viv get placed
onto the alter. Bastion was able to save everyone by the grace of hit dice to
get people up. Now its time for a short rest. Viv then talks with bastion
about leaving and hands him some letters as she hugs him.. sad music plays.

* 2023/02/19 - Sessions Notes
Viv has left the party and zamon walked in crying from the letter that viv left
for him. Shortly after we hear someone calling out saying "Good job on your
adventures, but if you want to keep having them hand over the amulet to us."

zariah and illiana said they would go and check out what is going on outside of
the statue. Jag also went out to go investigate. As that happens i hear spells
being cast outside of the statue. With a sigh i go out to the entrance and
yell "what is going on out here!?!", zariah replies "These guys are attacking us"
Turning around i call back down the hall "Get your lazy bones up were fighting!!"
From the ceiling rise of the Valkyries fills the air as a purple teifling
descends from above. Casting shatter on the ground then saying "Sible" (good in
French). The enemy firs back as multiple file out from behind the other statues.
They go over and slash at illiana, thankfully missing here by a hairs length.
Like a rocket stillben dashes out of the entrance of the statue, jumps and
landed behind a bugbear and he thwacks him with his staff. Jag runs up and
stabs one of the goblins. I climb down from the statue as my toll of the dead
are continually saved. Frustration wells out of me. Out of no where all i see
is darkness. AHHHHHHHH as i awake to a tiny baboon healing me as i feel all of
my health come back and my divine abilities rejuvenated. The muscles contract
as i feel my powers increase (lvl up to 7). I run over to zamon and get him up
by sparing him and then healing him by saying "May god smile on thee" as he
gets up, everyone seems to still be fine, i'm not sure what happened to us but
everything seems okay now. Stillben is up as well even though i remember
him being down. The baboon did give him some sort of weirdly colored liquid.
The tide of the battles looks to have shifted as most of the people who
ambushed us have been killed as the rest try to run away. Unfortunately
for them we trapped one of the people and tied them up. They do not
seem like they want to be on this plane of existence anymore. As I
stand over the prisoner i say "If god wills it, then god wills it." As
I start to say a dwarven prayer over the prisoner as Zamon shoots her in
the head with his crossbow.
