#+LATEX_CLASS: dnd
#+STARTUP: content showstars indent
#+OPTIONS: tags:nil
#+TITLE: Avadra Gahdouhs's Abilities
#+FILETAGS: avadra gahdouh abilities

* Class ([[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Ranger][Ranger]])                                                        :pbh:
** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Favored Foe][Favored Foe]]                              :lvl_1:lvl_6:lvl_14:alt_feature:
- Description ::
  Hit an attack you can mark the enemy.

- Damage ::
  1d4 (1d6, 1d8)

- Duration ::
  1 Minute

- Proficiency Usages ::  
|------+---+---|
| Used | 0 | 4 |
|------+---+---|

** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Natural Explorer][Natural Explorer]]                                     :lvl_1:lvl_6:lvl_10:
- Description ::
  Proficient INT or WIS checks related to favored terrain.
  Expertise if proficient

|---------+-------+---+---|
| Terrain | Swamp | ` | ` |
|---------+-------+---+---|

** Fighting Style
|---------|
| Defense |
|---------|


** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Primeval Awareness][Primeval Awareness]]                                                :lvl_3:

** Ability Score Improvement

| Level | Type | Value  |
|-------+------+--------|
|     4 | ASI  | +2 DEX |

** Archetype (Gloom stalker)                            :xgte:gloom_stalker:

| Ranger Level | Spells        |
|--------------+---------------|
| 3rd          | [[file:~/.emacs.d/ignore/org-dnd/10.spells.org::Disguise Self][Disguise Self]] |

*** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Dread Ambusher][Dread Ambusher]]                                                  :lvl_3:
- Descripton ::
  Initiative +WIS MOD

  1st turn of combat
  - +10ft movement.
  - 1d8 on attack action

*** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Umbral Sight][Umbral Sight]]                                         :lvl_3:darkvision:
- Descripton ::
  Darkvision 60ft. +30ft if you have darkvision

  Invisible to creatures relying on dark vision to see you in the dark.

* Class ([[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Cleric][Cleric]])                                                       :tcoe:
** Domain
|--------+----------|
| Domain | Twilight |
|--------+----------|

The banished one is my god and she poses as a fair skinned lady with
twilight eyes and a fierce temper.

*** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Eyes of Night][Eyes of Night]]                                                   :lvl_1:
- Description ::
  - 300ft darkvision. Grant to WIS MOD # of creatures.
  - Lasts 1 hour.
  - Long rest to reset.

  |------+---+---|
  | Uses | 0 | 1 |
  |------+---+---|

*** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Vigilant Blessing][Vigilant Blessing]]                                               :lvl_1:
- Description ::
  Grant advantage on initiative as an action.
  
* Class ([[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Monk][Monk]])                                                          :phb:
** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Martial Arts][Martial Arts]]                                                      :lvl_1:
- Description ::
   - DEX MOD on monk weapons.

   - With Monk Weapon or Unarmed strikes
     - Martial Arts Die (1d6 currently)
     - Attack action, use bonus action to make an unarmed strike.

** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Unarmored Defense][Unarmored Defense]]                                                 :lvl_1:
- Description ::
  No armor or shield. AC equals 10 + DEX MOD + WIS MOD

** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Ki][Ki]]                                                                :lvl_2:
- Description ::
  - Reset :: long or short rest to gain all back.
  - Ki save DC :: 8 + PB + WIS MOD
    
  - 1 Ki point for a bonus action on your turn
    - Flurry of Blows
      Make two unarmed strikes after attack action.

    - Patient Defense
      Dodge action.

    - Step of the Wind
      Disengage or Dash action, jump distance is doubled for the turn.

|------+---+---|
| Used | 0 | 6 |
|------+---+---|
      
** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Unarmored Movement][Unarmored Movement]]                                          :lvl_2:lvl_9:
- Description ::
  Increase speed {based on level} without armor or shield.

  Level 9 run on vertical surfaces and water.
  
** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Deflect Missiles][Deflect Missiles]] :lvl_3:
- Description ::
  Decrease hit ranged attack 1d10 + DEX MOD + Monk level (10).

  Projectile is caught when the damage is reduced to 0.

  1 ki point to throw the caught projectile. Range 20/60

** Monastic Tradition ([[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Way of the Shadow][Way of the Shadow)]]                              :phb:
*** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Shadow Arts][Shadow Arts]]                                                     :lvl_3:
- Description ::
  2 ki points to cast from table. Minor Illusion cantrip.

  | Spells             |
  |--------------------|
  | Darkness           |
  | Darkvision         |
  | Pass without trace |
  | Silence            |

*** Shadow Step
At 6th level, you gain the ability to step from one shadow into another. When
you are in dim light or darkness, as a bonus action you can teleport up to 60
feet to an unoccupied space you can see that is also in dim light or darkness.
You then have advantage on the first melee attack you make before the end of
the turn.

** ASI :lvl_4:
| level | type | value  |
|-------+------+--------|
|     4 | asi  | +2 dex |

** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Quickened Healing][Quickened Healing (Optional)]] :lvl_4:
- Description ::
  2 Ki points - Martial Arts Die + Proficiency

** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Slow Fall][Slow Fall]] :lvl_4:
- Description ::
  Reduce fall damage 5 * MONK LEVEL  

** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Stunning Strike][Stunning Strike]] :lvl_5:
- Description ::
  On successful hit, 1 Ki point to stun the enemy.

  - Saving throw :: CON (KI saving throw)

** Ki-Empowered Strikes
Starting at 6th level, your unarmed strikes count as magical for the purpose of
overcoming resistance and immunity to nonmagical attacks and damage.

* Racial (Shadar-Kai)
** Blessing of the Raven Queen.
As a bonus action, you can magically teleport up to 30 feet to an unoccupied
space you can see. You can use this trait a number of times equal to your
proficiency bonus, and you regain all expended uses when you finish a long rest.

- Starting at 3rd level ::
  you also gain resistance to all damage when you teleport using this trait. The
  resistance lasts until the start of your next turn. During that time, you
  appear ghostly and translucent.

|------+---+---|
| Used | 0 | 4 |
|------+---+---|

* God mode
** Temnota's Avatarl
Once per day you can use an action to expend 1 use of your channel divinity and
call upon the powers of the raven queen and cloak yourself within her darkness.
When you do, for 1 minute your entire body becomes draped in shadow and has the
following properties: 

- Erased presence ::
  When in darkness you are invisible and are able to erase your presence. Only a
  creature with True sight is able to see you

- Amorphus ::
  You can move through a space as narrow as 1 inch wide without squeezing

- Sunlight Weakness ::
  While in sunlight, the shadow has disadvantage on attack rolls, ability checks,
  and saving throws

- Advantage against being frightened

Eclipse: As an action you shroud an area you see within 60 feet of you in
darkness (requires concentration), while maintaining concentration you can use
your bonus action on subsequent turns to move the darkness to another point you
can see in range

- Shadow step ::
As a bonus action you can teleport via the shadows choosing a
point within 60 feet of you

- Face of death ::
When you reduce a creature to 0 hit points all other creature's within 30 feet
of you must make a WIS save against your spell DC. On a failed save the creature
is frightened, on a success the creature is immune to this effect until the next
dawn. You gain a number of temp HP equal to your proficiency bonus + the number
of creatures frightened. Your Allies have ADV against this save and if your in
darkness enemies have disadvantage. 

Once the minute is up you must make a CON save DC 10 on a fail you gain 2 levels
of exhaustion as your body is drained from overexhertion. On a success you
aren't exhausted but the DC increases by 1 each time you succeed. The DC resets
to 10 on a failed save.
