#+LATEX_CLASS: dnd
#+STARTUP: content showstars indent
#+OPTIONS: tags:nil
#+TITLE: Bo Grimspine's Equipment Sheet
#+FILETAGS: bo grimespine character sheet

* Starting equipment
| Equipment            | Quantity |
|----------------------+----------|
| Warhammer            |        1 |
| Chain mail           |        1 |
| Shield               |        1 |
| Explorer's Pack      |        1 |
| Amulet (Holy Symbol) |        1 |
| Dagger               |        1 |
| Deck of Cards        |        1 |
| Common Cloths        |        1 |
| Pouch of gold        |    10 GP |

* Jewel of Three Prayers (Dormant)
Wondrous item, legendary (requires attunement)

- Weight ::
  --
    
- Cost ::
  --

The Jewel of Three Prayers is a Vestige of Divergence (see the “Vestiges of
Divergence” sidebar). In ancient times, Alyxian the Apotheon bore this amulet
as a symbol of his covenant with three Prime Deities: Sehanine the Moon Weaver,
Avandra the Change Bringer, and Corellon the Arch Heart. When the jewel is
found, only Sehanine’s power thrums within its dormant heart. The power of the
other two deities waits to be reawakened by a hero—or heroes—who can follow in
Alyxian’s footsteps.

- Dormant State ::
  In this state, the Jewel of Three Prayers is a glittering golden disk attached
  to a fine golden chain. The chain magically resizes to function as a necklace
  for the creature that wears it.

In its Dormant State, the jewel has the following properties:

- You gain a +1 bonus to AC while wearing the jewel.
  
- While wearing or holding the jewel, you can use an action to cause it to shed
  bright light in a 15-foot radius and dim light for an additional 15 feet. The
  light lasts until you extinguish it (no action required).

- The jewel has 3 charges and regains all its expended charges daily at dawn.
  While holding the jewel, you can expend 1 charge from it to cast the
  invisibility spell.

* Potion of Vitality
When you drink this potion, it removes any exhaustion you are suffering and
cures any disease or poison affecting you. For the next 24 hours, you regain the
maximum number of hit points for any Hit Die you spend. The potion's crimson
liquid regularly pulses with dull light, calling to mind a heartbeat.
