b#+LATEX_CLASS: dnd
#+STARTUP: content showstars indent
#+OPTIONS: tags:nil
#+TITLE: Avadra Gahdouh Features Sheet
#+FILETAGS: avadra gahdouh features feature sheet

* Starting Stats
| Ability | Score |
|---------+-------|
| STR     |     8 |
| DEX     |    15 |
| CON     |    13 |
| INT     |    12 |
| WIS     |    14 |
| CHA     |    10 |

* Racial (Shadar-Kai)                                                  :race:
Shadar-kai are the elves of the Shadowfell, originally drawn to that dread realm
by the Raven Queen. Over the centuries, some of them have continued to serve
her, while others have ventured into the Material Plane to forge their own
destinies.

Once shadar-kai were Fey like the rest of their elven kin; now they exist in a
state between life and death, thanks to being transformed by the Shadowfell’s
grim energy.

Shadar-kai have ashen skin tones, and while they’re in the Shadowfell, they also
become wizened, reflecting the somber nature of that gloomy plane.

** Age                                                                 :age:
Like other elves, shadar-kai can live to be over 750 years old.

** Ability Score Increase                                              :asi:
When determining your character’s ability scores,
increase one score by 2 and increase a different score by 1, or increase three
different scores by 1. You can't raise any of your scores above 20.

| Type | Value  | Reason |
|------+--------+--------|
| ASI  | +1 DEX |        |
| ASI  | +2 WIS |        |

** Creature Type                                                      :type:
You are a Humanoid. You are also considered an elf for any prerequisite or
effect that requires you to be an elf.

** Size                                                               :size:
You are Medium.

** Speed                                                             :speed:
Your walking speed is 30 feet.

** Blessing of the Raven Queen                                     :ability:
As a bonus action, you can magically teleport up to 30 feet to an unoccupied
space you can see. You can use this trait a number of times equal to your
proficiency bonus, and you regain all expended uses when you finish a long rest.

- Starting at 3rd level ::
  you also gain resistance to all damage when you teleport using this trait. The
  resistance lasts until the start of your next turn. During that time, you
  appear ghostly and translucent.

** Darkvision                                                       :senses:
You can see in dim light within 60 feet of you as if it were bright light, and
in darkness as if it were dim light. You discern colors in that darkness only as
shades of gray.

** Fey Ancestry                                                     :legacy:
You have advantage on saving throws you make to avoid or end the charmed
condition on yourself.

** Keen Senses                                                      :senses:
You have proficiency in the Perception skill.

** Necrotic Resistance                                 :necrotic:resistance:
You have resistance to necrotic damage.

** Trance                                                    :magical_sleep:
You don’t need to sleep, and magic can’t put you to sleep. You can finish a long
rest in 4 hours if you spend those hours in a trancelike meditation, during
which you retain consciousness.

- Whenever you finish this trance, you can gain two proficiencies that you don’t
  have, each one with a weapon or a tool of your choice selected from the
  Player’s Handbook. You mystically acquire these proficiencies by drawing them
  from shared elven memory, and you retain them until you finish your next long
  rest.

|-------------------|
| Proficient        |
|-------------------|
| Brewer's Supplies |
| Short bow         |
|-------------------|
 
** Languages.
Your character can speak, read, and write Common and one other language that you
and your DM agree is appropriate for the character. The Player’s Handbook offers
a list of languages to choose from. The DM is free to modify that list for a
campaign.
