b#+LATEX_CLASS: dnd
#+STARTUP: content showstars indent
#+OPTIONS: tags:nil
#+TITLE: Bo Grimspine's Features Sheet
#+FILETAGS: bo grimspine features racial sheet

* Starting Stats
| Ability | Score |
|---------+-------|
| STR     |    14 |
| DEX     |    10 |
| CON     |    13 |
| INT     |     8 |
| WIS     |    15 |
| CHA     |    12 |

* Racial (Dwarf)
Your dwarf character has an assortment of inborn abilities, part and parcel of
dwarven nature.

** Ability Score Increase                                          :asi:con:
Your Constitution score increases by 2. 

** Age                                                                 :age:
Dwarves mature at the same rate as humans, but they’re considered young until
they reach the age of 50. On average, they live about 350 years.

** Size                                                               :size:
Dwarves stand between 4 and 5 feet tall and average about 150 pounds. Your size
is Medium.

** Speed                                                             :speed:
Your base walking speed is 25 feet. Your speed is not reduced by wearing heavy
armor.

** Darkvision                                                       :senses:
Accustomed to life underground, you have superior vision in dark and dim
conditions. You can see in dim light within 60 feet of you as if it were bright
light, and in darkness as if it were dim light. You can’t discern color in
darkness, only shades of gray.

** Dwarven Resilience                                     :advantage:poison:
You have advantage on saving throws against poison, and you have resistance
against poison damage (explained in the “Combat” section).

** Dwarven Combat Training
You have proficiency with the battleaxe, handaxe, light hammer, and warhammer.

** Tool Proficiency                    :proficiency_tool:smith:brewer:mason:
You gain proficiency with the artisan’s tools of your choice: smith’s tools,
brewer’s supplies, or mason’s tools.

** Stonecunning                                    :advantage:stone:history:
Whenever you make an Intelligence (History) check related to the origin of
stonework, you are considered proficient in the History skill and add double
your proficiency bonus to the check, instead of your normal proficiency bonus.

** Languages                                                      :language:
You can speak, read, and write Common and Dwarvish. Dwarvish is full of hard
consonants and guttural sounds, and those characteristics spill over into
whatever other language a dwarf might speak.

| Type | Value  | Reason |
|------+--------+--------|
| ASI  | +2 CON |        |

* Racial (Hill Dwarf)
As a hill dwarf, you have keen senses, deep intuition, and remarkable
resilience. The gold dwarves of Faerûn in their mighty southern kingdom are hill
dwarves, as are the exiled Neidar and the debased Klar of Krynn in the
Dragonlance setting.

** Ability Score Increase                                          :asi:wis:
Your Wisdom score increases by 1.

** Dwarven Toughness                                                    :hp:
Your hit point maximum increases by 1, and it increases by 1 every time you gain
a level.

| Type | Value  | Reason |
|------+--------+--------|
| ASI  | +1 WIS |        |
