#+LATEX_CLASS: dnd
#+STARTUP: content showstars indent
#+OPTIONS: tags:nil
#+TITLE: Avadra's Spells
#+FILETAGS: avadra gahdouh spells

* Cantrips
** Spare the Dying                            :artificer:cleric:cantrip:pbh:
Necromancy cantrip

Casting Time: 1 action
Range: Touch
Components: V, S
Duration: Instantaneous

You touch a living creature that has 0 hit points. The creature becomes stable.
This spell has no effect on undead or constructs.   

** Guidance                             :artificer:cleric:druid:cantrip:pbh:
Divination cantrip

Casting Time: 1 action
Range: Touch
Components: V, S
Duration: Concentration, up to 1 minute

You touch one willing creature. Once before the spell ends, the target can roll
a d4 and add the number rolled to one ability check of its choice. It can roll
the die before or after making the ability check. The spell then ends

** Minor Illusion                 :bard:sorcerer:warlock:wizard:cantrip:pbh:
Illusion cantrip

Casting Time: 1 action
Range: 30 feet
Components: S, M (a bit of fleece)
Duration: 1 minute

You create a sound or an image of an object within range that lasts for the
duration. The illusion also ends if you dismiss it as an action or cast this
spell again.

If you create a sound, its volume can range from a whisper to a scream. It can
be your voice, someone else’s voice, a lion’s roar, a beating of drums, or any
other sound you choose. The sound continues unabated throughout the duration, or
you can make discrete sounds at different times before the spell ends.

If you create an image of an object—such as a chair, muddy footprints, or a
small chest—it must be no larger than a 5-foot cube. The image can’t create
sound, light, smell, or any other sensory effect. Physical interaction with the
image reveals it to be an illusion, because things can pass through it.

If a creature uses its action to examine the sound or image, the creature can
determine that it is an illusion with a successful Intelligence (Investigation)
check against your spell save DC. If a creature discerns the illusion for what
it is, the illusion becomes faint to the creature.

** Thaumaturgy                                          :cleric:cantrip:pbh:
Transmutation cantrip

Casting Time: 1 action
Range: 30 feet
Components: V
Duration: Up to 1 minute

You manifest a minor wonder, a sign of supernatural power, within range. You
create one of the following magical effects within range:

- Your voice booms up to three times as loud as normal for 1 minute.

- You cause flames to flicker, brighten, dim, or change color for 1 minute.

- You cause harmless tremors in the ground for 1 minute.

- You create an instantaneous sound that originates from a point of your choice
  within range, such as a rumble of thunder, the cry of a raven, or ominous
  whispers.

- You instantaneously cause an unlocked door or window to fly open or slam shut.

- You alter the appearance of your eyes for 1 minute.

If you cast this spell multiple times, you can have up to three of its 1-minute
effects active at a time, and you can dismiss such an effect as an action.

* 1st Level

|------+---+---+---+---|
| Used |   |   |   |   |
|------+---+---+---+---|

** Alarm                                 :artificer:ranger:wizard:lvl_1:pbh:
1st-level abjuration (ritual)

Casting Time: 1 action
Range: 30 feet
Components: V, S, M (a tiny bell and a piece of fine silver wire)
Duration: 8 hours

You set an alarm against unwanted intrusion. Choose a door, a window, or an area
within range that is no larger than a 20-foot cube. Until the spell ends, an
alarm alerts you whenever a tiny or larger creature touches or enters the warded
area. When you cast the spell, you can designate creatures that won’t set off
the alarm. You also choose whether the alarm is mental or audible.

A mental alarm alerts you with a ping in your mind if you are within 1 mile of
the warded area. This ping awakens you if you are sleeping. An audible alarm
produces the sound of a hand bell for 10 seconds within 60 feet.

** Detect Evil and Good :cleric:paladin:lvl_1:pbh:
1st-level divination

Casting Time: 1 action
Range: Self
Components: V, S
Duration: Concentration, up to 10 minutes

For the duration, you know if there is an aberration, celestial, elemental, fey,
fiend, or undead within 30 feet of you, as well as where the creature is
located. Similarly, you know if there is a place or object within 30 feet of you
that has been magically consecrated or desecrated.

The spell can penetrate most barriers, but it is blocked by 1 foot of stone, 1
inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.

** Detect Magic :artificer:bard:cleric:druid:paladin:ranger:sorcerer:wizard:lvl_1:pbh:
1st-level divination (ritual)

Casting Time: 1 action
Range: Self
Components: V, S
Duration: Concentration, up to 10 minutes

For the duration, you sense the presence of magic within 30 feet of you. If you
sense magic in this way, you can use your action to see a faint aura around any
visible creature or object in the area that bears magic, and you learn its
school of magic, if any.

The spell can penetrate most barriers, but is blocked by 1 foot of stone, 1 inch
of common metal, a thin sheet of lead, or 3 feet of wood or dirt.

** Disguise Self                  :artificer:bard:sorcerer:wizard:lvl_1:pbh:
1st-level illusion

Casting Time: 1 action
Range: Self
Components: V, S
Duration: 1 hour

You make yourself – including your clothing, armor, weapons, and other
belongings on your person – look different until the spell ends or until you use
your action to dismiss it. You can seem 1 foot shorter or taller and can appear
thin, fat, or in between. You can’t change your body type, so you must adopt a
form that has the same basic arrangement of limbs. Otherwise, the extent of the
illusion is up to you.

The changes wrought by this spell fail to hold up to physical inspection. For
example, if you use this spell to add a hat to your outfit, objects pass through
the hat, and anyone who touches it would feel nothing or would feel your head
and hair. If you use this spell to appear thinner than you are, the hand of
someone who reaches out to touch you would bump into you while it was seemingly
still in midair. To discern that you are disguised, a creature can use its
action to inspect your appearance and must succeed on an Intelligence
(Investigation) check against your spell save DC.

** Faerie Fire                              :artificer:bard:druid:lvl_1:pbh:
1st-level evocation

Casting Time: 1 action
Range: 60 feet
Components: V
Duration: Concentration, up to 1 minute

Each object in a 20-foot cube within range is outlined in blue, green, or violet light (your choice).

Any creature in the area when the spell is cast is also outlined in light if it fails a Dexterity saving throw. For the duration, objects and affected creatures shed dim light in a 10-foot radius.

Any attack roll against an affected creature or object has advantage if the attacker can see it, and the affected creature or object can’t benefit from being invisible.

** Goodberry                                        :druid:ranger:lvl_1:pbh:
1st-level transmutation

Casting Time: 1 action
Range: Touch
Components: V, S, M (a sprig of mistletoe)
Duration: Instantaneous

Up to ten berries appear in your hand and are infused with magic for the duration. A creature can use its action to eat one berry. Eating a berry restores 1 hit point, and the berry provides enough nourishment to sustain a creature for one day.

The berries lose their potency if they have not been consumed within 24 hours of the casting of this spell.

** Healing Word                                :bard:cleric:druid:lvl_1:pbh:
1st-level evocation

Casting Time: 1 bonus action
Range: 60 feet
Components: V
Duration: Instantaneous

A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier. This spell has no effect on undead or constructs.

At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d4 for each slot level above 1st.

** Hunter's Mark :ranger:lvl_1:pbh:
1st-level divination

Casting Time: 1 bonus action
Range: 90 feet
Components: V
Duration: Concentration, up to 1 hour

You choose a creature you can see within range and mystically mark it as your quarry. Until the spell ends, you deal an extra 1d6 damage to the target whenever you hit it with a weapon attack, and you have advantage on any Wisdom (Perception) or Wisdom (Survival) check you make to find it.

If the target drops to 0 hit points before this spell ends, you can use a bonus action on a subsequent turn of yours to mark a new creature.

At Higher Levels. When you cast this spell using a spell slot of 3rd or 4th level, you can maintain your concentration on the spell for up to 8 hours. When you use a spell slot of 5th level or higher, you can maintain your concentration on the spell for up to 24 hours.

** Shield of Faith :cleric:paladin:lvl_1:pbh:
1st-level abjuration

Casting Time: 1 bonus action
Range: 60 feet
Components: V, S, M (a small parchment with a bit of holy text written on it)
Duration: Concentration, up to 10 minutes

A shimmering field appears and surrounds a creature of your choice within range, granting it a +2 bonus to AC for the duration.

** Sleep :bard:sorcerer:wizard:lvl_1:pbh:
1st-level enchantment

Casting Time: 1 action
Range: 90 feet
Components: V, S, M (a pinch of fine sand, rose petals, or a cricket)
Duration: 1 minute

This spell sends creatures into a magical slumber. Roll 5d8, the total is how many hit points of creatures this spell can affect. Creatures within 20 feet of a point you choose within range are affected in ascending order of their current hit points (ignoring unconscious creatures).

Starting with the creature that has the lowest current hit points, each creature affected by this spell falls unconscious until the spell ends, the sleeper takes damage, or someone uses an action to shake or slap the sleeper awake. Subtract each creature’s hit points from the total before moving on to the creature with the next lowest hit points. A creature’s hit points must be equal to or less than the remaining total for that creature to be affected. Undead and creatures immune to being charmed aren’t affected by this spell.

At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, roll an additional 2d8 for each slot level above 1st.

* 2nd Level

|------+---+---|
| Used |   |   |
|------+---+---|

** Darkness :sorcerer:warlock:warlock:lvl_2:pbh:
Casting Time: 1 action
Range: 60 feet
Components: V, M (bat fur and a drop of pitch or piece of coal)
Duration: Concentration, up to 10 minutes

Magical darkness spreads from a point you choose within range to fill a 15-foot radius sphere for the duration. The darkness spreads around corners. A creature with darkvision can’t see through this darkness, and nonmagical light can’t illuminate it.

If the point you choose is on an object you are holding or one that isn’t being worn or carried, the darkness emanates from the object and moves with it. Completely covering the source of the darkness with an opaque object, such as a bowl or a helm, blocks the darkness.

If any of this spell’s area overlaps with an area of light created by a spell of 2nd level or lower, the spell that created the light is dispelled.

** Darkvision :artificer:druid:ranger:sorcerer:wizard:lvl_2:pbh:
2nd-level transmutation

Casting Time: 1 action
Range: Touch
Components: V, S, M (either a pinch of dried carrot or an agate)
Duration: 8 hours

You touch a willing creature to grant it the ability to see in the dark. For the duration, that creature has darkvision out to a range of 60 feet.

** Pass without Trace :druid:ranger:lvl_2:pbh:
2nd-level abjuration

Casting Time: 1 action
Range: Self
Components: V, S, M (ashes from a burned leaf of mistletoe and a sprig of spruce)
Duration: Concentration, up to 1 hour

A veil of shadows and silence radiates from you, masking you and your companions from detection. For the duration, each creature you choose within 30 feet of you (including you) has a +10 bonus to Dexterity (Stealth) checks and can’t be tracked except by magical means. A creature that receives this bonus leaves behind no tracks or other traces of its passage.

** Silence :bard:cleric:ranger:lvl_2:pbh:
2nd-level illusion (ritual)

Casting Time: 1 action
Range: 120 feet
Components: V, S
Duration: Concentration, up to 10 minutes

For the duration, no sound can be created within or pass through a 20-foot-radius sphere centered on a point you choose within range. Any creature or object entirely inside the sphere is immune to thunder damage, and creatures are deafened while entirely inside it. Casting a spell that includes a verbal component is impossible there.
