b#+LATEX_CLASS: dnd
#+STARTUP: content showstars indent
#+OPTIONS: tags:nil
#+TITLE: Leap Ledger Features Sheet
#+FILETAGS: leap ledger features feature sheet

* Background
Starting Stats
| Ability | Score |
|---------+-------|
| STR     |     8 |
| DEX     |    14 |
| CON     |    14 |
| INT     |    10 |
| WIS     |    15 |
| CHA     |    10 |

** Background Ability
*** Ruined
https://dnd5e.wikidot.com/background:ruined

Everything was going so well! You had a life of luxury, love, and comfort when
you suddenly lost it all. Perhaps you were framed for crimes you didn’t commit
and lost your reputation, fortune, and career. Maybe a rampaging dragon or
another monster wiped out everything you had in a single calamitous afternoon.
Or you might have sought out a Deck of Many Things, hoping to make your successful
life even more glorious—only to draw a destructive card that changed your
destiny forever.

Your desperation has driven you to the career of adventurer. You don’t seek out
dark dungeons and their monstrous inhabitants for excitement and glory; you do
it because every other path is closed to you. But you have risen high on
fortune’s wheel once before, and with luck and fortitude, you could do so again.

- Skill Proficiencies ::
  Stealth, Survival

- Languages :: One of your choice

- Tool Proficiencies ::
  One gaming set of your choice (such as playing cards or three-dragon ante cards)

- Equipment ::
  A cracked hourglass, a set of rusty manacles, a half-empty bottle, a hunting
  trap, a gaming set (matching your chosen proficiency), a set of traveler’s
  clothes, and a pouch containing 13 gp

**** Feature: Still Standing
You have weathered ruinous misfortune, and you possess hidden reserves others
don’t expect. You gain the Alert, Skilled, or Tough feat (your choice). Your
choice of feat reflects how you’ve dealt with the terrible loss that changed
your life forever. If you’ve kept your senses sharp for every opportunity and
climbed your way out of misery by seizing the tiniest scrap of hope, choose
Alert. If you’ve redoubled your efforts to reclaim what was once yours,
choose Skilled. If you’ve stoically persevered through your misfortune,
select Tough.


*** |------+--------+--------|
| Type | Value  | Reason |
|------+--------+--------|
| ASI  | +1 WIS |        |
| ASI  | +2 DEX |        |
|------+--------+--------|


** Back story


** Alignment
Neutral

** Physical Characteristics
*** Hair
none

*** Skin
Purple

*** Eyes
Green

*** Height


*** Weight


*** Age (Years)


*** Gender
Male

*** Deity


* Features
** Racial (Grung)
- Amphibious ::
  You can breathe air and water
    
- Poison Immunity ::
  You are immune to poison damage and the poisoned condition
    
- Poison Skin ::
  Any creature that grapples you or otherwise comes into direct contact with your skin
  must succeed on a DC 12 Constitution saving throw or become poisoned for 1 minute. A
  poisoned creature no longer in direct contact with you can repeat the saving throw
  at the end of each of its turns, ending the effect on itself on a success.
    
  - You can also apply this poison to any piercing weapon as part of an attack with
    that weapon, though when you hit the poison reacts differently. The target must
    succeed on a DC 12 Constitution saving throw or take 2d4 poison damage.
      
  - Purple ::
    The Poisoned creature feels a desperate need to soak itself in
    liquid or mud. It can’t take Actions or move except to do so or to reach a
    body of liquid or mud.
      
- Standing Leap ::
  Your long jump is up to 25 feet and your high jump is up to 15 feet, with or without
  a running start.
    
- Water Dependency ::
  If you fail to immerse yourself in water for at least 1 hour during a day


** Ability Score Increase                                              :asi:
When determining your character’s ability scores,
increase one score by 2 and increase a different score by 1, or increase three
different scores by 1. You can't raise any of your scores above 20.

|------+-------+--------|
| Type | Value | Reason |
|------+-------+--------|
| ASI  |    +1 |        |
| ASI  |    +2 |        |
|------+-------+--------|


|------------|
| Proficient |
|------------|
|            |
|------------|

