#+STARTUP: content showstars indent
#+FILETAGS: dnd notes sir tan
* The note from the sisters
The elveswhere town is where they said to look them up eboline and valentine?
/Entered on/ [2023-09-10 Sun 18:29]
* People i'm with

Arres, Fayreess, Thezbeen, alair, thumb thumb
/Entered on/ [2023-09-10 Sun 18:44]
* We woke up without memories in a carnival

From there we were sent on a mission to go to prismeer to look for thought theives.
/Entered on/ [2023-09-10 Sun 18:55]
* Run into lecia the giant messenger with a purple sythe
The messenger created a path for us to stay on to make out way to elveswhere.
/Entered on/ [2023-09-10 Sun 18:58]
* Campfire
Thezbeen said his only heartbreak was his parents

Fayress wants magic to be controlled and not be misused.

Im looking to find sir rueben to find the best sandwich maker

Fayress has a pet peeve about people not burying their defecation. Then fayress would put your hand in water while you are sleeping to make you pee yourself

Arress really likes to watch peoples be doing things.

Alair doesn't believe in free will, but believes that everything is fated
/Entered on/ [2023-09-10 Sun 19:11]
* The egg has hatched
The bird that came out of the egg was named phyluss
/Entered on/ [2023-09-10 Sun 19:42]
* Made it to the town of elveswhere
Met the minotaur in charge named Dom. He told us about the murders at the gates and whatever did it ran into the sewers
/Entered on/ [2023-09-10 Sun 19:57]

* After defeating the mud monster
Dom told us to meet him at the good knight which is a bar and inn. They also do alot of fights.
