#+LATEX_CLASS: dnd
#+STARTUP: content showstars indent
#+OPTIONS: tags:nil
#+TITLE: Sir Tan's Abilities
#+FILETAGS: sir tan abilities

* Class ([[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Paladin][Paladin]]) :pbh:
** Divine Sense
The presence of strong evil registers on your senses like a noxious odor, and
powerful good rings like heavenly music in your ears. As an action, you can open
your awareness to detect such forces. Until the end of your next turn, you know
the location of any celestial, fiend, or undead within 60 feet of you that is
not behind total cover. You know the type (celestial, fiend, or undead) of any
being whose presence you sense, but not its identity (the vampire Count Strahd
von Zarovich, for instance). Within the same radius, you also detect the
presence of any place or object that has been consecrated or desecrated, as
with the Hallow spell.

You can use this feature a number of times equal to 1 + your Charisma modifier.
When you finish a long rest, you regain all expended uses.

** Lay on Hands
Your blessed touch can heal wounds. You have a pool of healing power that
replenishes when you take a long rest. With that pool, you can restore a
total number of hit points equal to your paladin level x 5.

As an action, you can touch a creature and draw power from the pool to restore a
number of hit points to that creature, up to the maximum amount remaining in
your pool.

Alternatively, you can expend 5 hit points from your pool of healing to cure the
target of one disease or neutralize one poison affecting it. You can cure
multiple diseases and neutralize multiple poisons with a single use of Lay on
Hands, expending hit points separately for each one.

This feature has no effect on undead and constructs.

|-------|
| Left  |
|-------|
| 15/15 |
|-------|

** Fighting Style
*** Tunnel Fighter (UA).
As a bonus action, you can enter a defensive stance that lasts until the start
of your next turn. While in your defensive stance, you can make opportunity
attacks without using your reaction, and you can use your reaction to make a
melee attack against a creature that moves more than 5 feet while within your
reach.

** Spellcasting
By 2nd level, you have learned to draw on divine magic through meditation and
prayer to cast spells as a cleric does.

*** Preparing and Casting Spells
The Paladin table shows how many spell slots you have to cast your paladin
spells. To cast one of your paladin spells of 1st level or higher, you must
expend a slot of the spell's level or higher. You regain all expended spell
slots when you finish a long rest.

You prepare the list of paladin spells that are available for you to cast,
choosing from the paladin spell list. When you do so, choose a number of paladin
spells equal to your Charisma modifier + half your paladin level, rounded down
(minimum of one spell). The spells must be of a level for which you have spell
slots.

For example, if you are a 5th-level paladin, you have four 1st-level and two
2nd-level spell slots. With a Charisma of 14, your list of prepared spells can
include four spells of 1st or 2nd level, in any combination. If you prepare the
1st-level spell Cure Wounds, you can cast it using a 1st-level or a 2nd-level
slot. Casting the spell doesn't remove it from your list of prepared spells.

You can change your list of prepared spells when you finish a long rest.
Preparing a new list of paladin spells requires time spent in prayer and
meditation: at least 1 minute per spell level for each spell on your list.

** Spellcasting Ability
Charisma is your spellcasting ability for your paladin spells, since their power
derives from the strength of your convictions. You use your Charisma whenever a
spell refers to your spellcasting ability. In addition, you use your Charisma
modifier when setting the saving throw DC for a paladin spell you cast and when
making an attack roll with one.

Spell save DC = 8 + your proficiency bonus + your Charisma modifier

Spell attack modifier = your proficiency bonus + your Charisma modifier

Spellcasting Focus
You can use a holy symbol as a spellcasting focus for your paladin spells.

** Divine Smite
Starting at 2nd level, when you hit a creature with a melee weapon attack, you
can expend one spell slot to deal radiant damage to the target, in addition to
the weapon's damage. The extra damage is 2d8 for a 1st-level spell slot, plus
1d8 for each spell level higher than 1st, to a maximum of 5d8. The damage
increases by 1d8 if the target is an undead or a fiend, to a maximum of 6d8.

* Sub-Class (Oath of the Crown)
** Channel Divinity

|------+---+---|
| Used | 0 | 1 |
|------+---+---|

When you take this oath at 3rd level, you gain the following two Channel
Divinity options.

*** Champion Challenge.
As a bonus action, you issue a challenge that compels other creatures to do
battle with you. Each creature of your choice that you can see within 30 feet of
you must make a Wisdom saving throw. On a failed save, a creature can't
willingly move more than 30 feet away from you. This effect ends on the creature
if you are incapacitated or die or if the creature is more than 30 feet away
from you.

*** Turn the Tide.
As a bonus action, you can bolster injured creatures with your Channel Divinity.
Each creature of your choice that can hear you within 30 feet of you regains hit
points equal to 1d6 + your Charisma modifier (minimum of 1) if it has no more
than half of its hit points.

* Racial (Centaur)
** Charge.
If you move at least 30 feet straight toward a target and then hit it with a
melee weapon attack on the same turn, you can immediately follow that attack
with a bonus action, making one attack against the target with your hooves.
** Hooves.
Your hooves are natural melee weapons, which you can use to make unarmed strikes.
If you hit with them, you deal bludgeoning damage equal to 1d4 + your Strength
modifier, instead of the bludgeoning damage normal for an unarmed strike.
 
