b#+LATEX_CLASS: dnd
#+STARTUP: content showstars indent
#+OPTIONS: tags:nil
#+TITLE: Avadra Gahdouh Features Sheet
#+FILETAGS: avadra gahdouh features feature sheet

* Starting Stats
(Point buy)

| Ability | Score |
|---------+-------|
| STR     |    14 |
| DEX     |    10 |
| CON     |    14 |
| INT     |    10 |
| WIS     |    10 |
| CHA     |    14 |

* Racial (Centaur) :race:guildmaster_guide_to_ravnica:mythic_odysseys_of_theros:

Roamers at heart, centaurs love open spaces and the freedom to travel. As much
as they can, centaurs run. They race the wind, hooves thundering and tails
streaming behind them.

** Ability Score Increase
Your Strength score increases by 2, and your Wisdom score increases by 1.

| Type | Value  |
|------+--------|
| ASI  | +2 STR |
| ASI  | +1 WIS |


** Age
Centaurs mature and age at about the same rate as humans.

** Alignment
Centaurs are inclined toward neutrality.

** Size
Centaurs stand between 6 and 7 feet tall, with their equine bodies reaching
about 4 feet at the withers. Your size is Medium.

** Speed
Your base walking speed is 40 feet.

** Fey
Your creature type is fey, rather than humanoid.

** Charge                                                          :ability:
If you move at least 30 feet straight toward a target and then hit it with a
melee weapon attack on the same turn, you can immediately follow that attack
with a bonus action, making one attack against the target with your hooves.

** Hooves                                                          :ability:
Your hooves are natural melee weapons, which you can use to make unarmed
strikes. If you hit with them, you deal bludgeoning damage equal to 1d4 +
your Strength modifier, instead of the bludgeoning damage normal for an
unarmed strike.

** Equine Build
You count as one size larger when determining your carrying capacity and the
weight you can push or drag. In addition, any climb that requires hands and feet
is especially difficult for you because of your equine legs. When you make such
a climb, each foot of movement costs you 4 extra feet, instead of the normal 1
extra foot.

** Survivor
You have proficiency in one of the following skills: Animal Handling, Medicine,
Nature, or Survival.

|------------|
| Proficient |
|------------|
| Survival   |
|------------|

** Languages
You can speak, read, and write Common and Sylvan.


* Class (Paladin)

** Proficiencies

- Armor :: All armor, shields

- Weapons :: Simple weapons, martial weapons

- Tools :: None

- Saving Throws :: Wisdom, Charisma

- Skills :: Choose two from Athletics, Insight, Intimidation, Medicine,
  Persuasion, and Religion

|--------------|
| Proficient   |
|--------------|
| Insight      |
| Intimidation |
|--------------|

