#+LATEX_CLASS: dnd
#+STARTUP: content showstars indent
#+OPTIONS: tags:nil
#+TITLE: Avadra's Spells
#+FILETAGS: avadra gahdouh spells

* 1st Level                                                           :lvl_1:

|------+---+---|
| Used | 0 | 3 |
|------+---+---|

** Compelled Duel (C)                                          :paladin:pbh:
1st-level enchantment

- Casting Time :: 1 bonus action
- Range :: 30 feet
- Components :: V
- Duration :: Concentration, up to 1 minute

You attempt to compel a creature into a duel. One creature that you can see
within range must make a Wisdom saving throw. On a failed save, the creature
is drawn to you, compelled by your divine demand. For the duration, it has
disadvantage on attack rolls against creatures other than you, and must make a
Wisdom saving throw each time it attempts to move to a space that is more than
30 feet away from you; if it succeeds on this saving throw, this spell doesn’t
restrict the target’s movement for that turn.

The spell ends if you attack any other creature, if you cast a spell that
targets a hostile creature other than the target, if a creature friendly to you
damages the target or casts a harmful spell on it, or if you end your turn more
than 30 feet away from the target.

** Command                                         :bard:cleric:paladin:pbh:
1st-level enchantment

- Casting Time :: 1 action
- Range :: 60 feet
- Components :: V
- Duration :: 1 round

You speak a one-word command to a creature you can see within range. The target
must succeed on a Wisdom saving throw or follow the command on its next turn.
The spell has no effect if the target is undead, if it doesn’t understand your
language, or if your command is directly harmful to it. Some typical commands
and their effects follow. You might issue a command other than one described
here. If you do so, the DM determines how the target behaves. If the target
can’t follow your command, the spell ends.

Approach. The target moves toward you by the shortest and most direct route,
ending its turn if it moves within 5 feet of you.

Drop. The target drops whatever it is holding and then ends its turn.

Flee. The target spends its turn moving away from you by the fastest available
means.

Grovel. The target falls prone and then ends its turn.

Halt. The target doesn’t move and takes no actions. A flying creature stays
aloft, provided that it is able to do so. If it must move to stay aloft, it
flies the minimum distance needed to remain in the air.

At Higher Levels. When you cast this spell using a spell slot of 2nd level or
higher, you can affect one additional creature for each slot level above 1st.
The creatures must be within 30 feet of each other when you target them.

** Wrathful Smite (C)                                          :paladin:pbh:
1st-level evocation

- Casting Time :: 1 bonus action
- Range :: Self
- Components :: V
- Duration :: Concentration, up to 1 minute

The next time you hit with a melee weapon attack during this spell’s duration,
your attack deals an extra 1d6 psychic damage. Additionally, if the target is a
creature, it must make a Wisdom saving throw or be frightened of you until the
spell ends. As an action, the creature can make a Wisdom check against your
spell save DC to steel its resolve and end this spell.

** Protection from Evil and Good (C)   :cleric:druid:paladin:warlock:wizard:
1st-level abjuration

- Casting Time :: 1 action
- Range :: Touch
- Components :: V, S, M (holy water or powdered silver and iron, which the spell consumes)
- Duration :: Concentration, up to 10 minutes

Until the spell ends, one willing creature you touch is protected against
certain types of creatures: aberrations, celestials, elementals, fey, fiends,
and undead.

The protection grants several benefits. Creatures of those types have
disadvantage on attack rolls against the target. The target also can't be
charmed, frightened, or possessed by them. If the target is already charmed,
frightened, or possessed by such a creature, the target has advantage on any new
saving throw against the relevant effect.
