#+LATEX_CLASS: dnd
#+STARTUP: content showstars indent
#+OPTIONS: tags:nil
#+TITLE: Bo Grimspine's Abilities
#+FILETAGS: bo grimspine abilities

* Class (Cleric) :pbh:

| Lvl | Cantrip | 1st | 2nd | 3rd | 4th | 5th | 6th | 7th | 8th | 9th |
|-----+---------+-----+-----+-----+-----+-----+-----+-----+-----+-----|
|   1 |       3 |   2 |     |     |     |     |     |     |     |     |
|   2 |       3 |   3 |     |     |     |     |     |     |     |     |
|   3 |       3 |   4 |   2 |     |     |     |     |     |     |     |
|   4 |       4 |   4 |   3 |     |     |     |     |     |     |     |
|   5 |       4 |   4 |   3 |   2 |     |     |     |     |     |     |
|   6 |       4 |   4 |   3 |   3 |     |     |     |     |     |     |
|   7 |       4 |   4 |   3 |   3 |   1 |     |     |     |     |     |
|   8 |       4 |   4 |   3 |   3 |   2 |     |     |     |     |     |
|   9 |       4 |   4 |   3 |   3 |   3 |   1 |     |     |     |     |
|  10 |       5 |   4 |   3 |   3 |   3 |   2 |     |     |     |     |
|  11 |       5 |   4 |   3 |   3 |   3 |   2 |   1 |     |     |     |
|  12 |       5 |   4 |   3 |   3 |   3 |   2 |   1 |     |     |     |
|  13 |       5 |   4 |   3 |   3 |   3 |   2 |   1 |   1 |     |     |
|  14 |       5 |   4 |   3 |   3 |   3 |   2 |   1 |   1 |     |     |
|  15 |       5 |   4 |   3 |   3 |   3 |   2 |   1 |   1 |   1 |     |
|  16 |       5 |   4 |   3 |   3 |   3 |   2 |   1 |   1 |   1 |     |
|  17 |       5 |   4 |   3 |   3 |   3 |   2 |   1 |   1 |   1 |   1 |
|  18 |       5 |   4 |   3 |   3 |   3 |   3 |   1 |   1 |   1 |   1 |
|  19 |       5 |   4 |   3 |   3 |   3 |   3 |   2 |   1 |   1 |   1 |
|  20 |       5 |   4 |   3 |   3 |   3 |   3 |   2 |   2 |   1 |   1 |

** Domain Spells 
Each domain has a list of spells-its domain spells that you gain at the cleric
levels noted in the domain description. Once you gain a domain spell, you always
have it prepared, and it doesn't count against the number of spells you can
prepare each day.

If you have a domain spell that doesn't appear on the cleric spell list, the
spell is nonetheless a cleric spell for you.

** Channel Divinity                                     :lvl_2:lvl_6:lvl_18:
At 2nd level, you gain the ability to channel divine energy directly from your
deity, using that energy to fuel magical effects. You start with two such
effects: Turn Undead and an effect determined by your domain. Some domains grant
you additional effects as you advance in levels, as noted in the domain
description.

When you use your Channel Divinity, you choose which effect to create. You must
then finish a short or long rest to use your Channel Divinity again.

Some Channel Divinity effects require saving throws. When you use such an effect
from this class, the DC equals your cleric spell save DC.

Beginning at 6th level, you can use your Channel Divinity twice between rests,
and beginning at 18th level, you can use it three times between rests. When you
finish a short or long rest, you regain your expended uses.

|------+---+---+---|
| Used | x | ` | ` |
|------+---+---+---|

** Channel Divinity: Turn Undead
As an action, you present your holy symbol and speak a prayer censuring the
undead. Each undead that can see or hear you within 30 feet of you must make a
Wisdom saving throw. If the creature fails its saving throw, it is turned for 1
minute or until it takes any damage.

A turned creature must spend its turns trying to move as far away from you as it
can, and it can't willingly move to a space within 30 feet of you. It also can't
take reactions. For its action, it can use only the Dash action or try to escape
from an effect that prevents it from moving. If there's nowhere to move, the
creature can use the Dodge action.

** Harness Divine Power (Optional)                      :lvl_2:lvl_6:lvl_18:
At 2nd level, you can expend a use of your Channel Divinity to fuel your spells.
As a bonus action, you touch your holy symbol, utter a prayer, and regain one
expended spell slot, the level of which can be no higher than half your
proficiency bonus (rounded up). The number of times you can use this feature is
based on the level you've reached in this class: 2nd level, once; 6th level,
twice; and 18th level, thrice. You regain all expended uses when you finish a
long rest.

** Ability Score Improvement              :lvl_4:lvl_8:lvl_12:lvl_16:lvl_19:
When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can
increase one ability score of your choice by 2, or you can increase two ability
scores of your choice by 1. As normal, you can't increase an ability score above
20 using this feature.

| Level | Type | Value            |
|-------+------+------------------|
|     4 | FEAT | Squat Nimbleness |
|     8 |      |                  |
|    12 |      |                  |
|    16 |      |                  |
|    19 |      |                  |


** Cantrip Versatility (Optional)                                  :cantrip:
Whenever you reach a level in this class that grants the Ability Score
Improvement feature, you can replace one cantrip you learned from this class's
Spellcasting feature with another cantrip from the cleric spell list.

** Destroy Undead                                                    :lvl_5:
Starting at 5th level, when an undead fails its saving throw against your Turn
Undead feature, the creature is instantly destroyed if its challenge rating is
at or below a certain threshold, as shown in the Cleric table above.

** Blessed Strikes (Optional)                                        :lvl_8:
Replaces the Divine Strike or Potent Spellcasting feature

When you reach 8th level, you are blessed with divine might in battle. When a
creature takes damage from one of your cantrips or weapon attacks, you can also
deal 1d8 radiant damage to that creature. Once you deal this damage, you can't
use this feature again until the start of your next turn.

** Divine Intervention                                       :lvl_10:lvl_20:
Beginning at 10th level, you can call on your deity to intervene on your behalf
when your need is great.

Imploring your deity's aid requires you to use your action. Describe the
assistance you seek, and roll percentile dice. If you roll a number equal to or
lower than your cleric level, your deity intervenes. The DM chooses the nature
of the intervention; the effect of any cleric spell or cleric domain spell would
be appropriate. If your deity intervenes, you can't use this feature again for 7
days. Otherwise, you can use it again after you finish a long rest.

At 20th level, your call for intervention succeeds automatically, no roll
required.
  
* Subclass (Forge Domain)                     :xanathars_guide_to_everything:

| Cleric Level | Spells                                   |
| 1st          | Identify, Searing Smite                  |
| 3rd          | Heat Metal, Magic Weapon                 |
| 5th          | Elemental Weapon, Protection from Energy |
| 7th          | Fabricated, Wall of Fire                 |
| 9th          | Animate Objects, Creation                |

** Bonus Proficiencies                                :pb:heavy_armor:smith:
When you choose this domain at 1st level, you gain proficiency with heavy armor
and smith's tools.

** Blessing of the Forge                                             :lvl_1:
At 1st level, you gain the ability to imbue magic into a weapon or armor. At the
end of a long rest, you can touch one nonmagical object that is a suit of armor
or a simple or martial weapon. Until the end of your next long rest or until you
die, the object becomes a magic item, granting a +1 bonus to AC if it’s armor or
a +1 bonus to attack and damage rolls if it’s a weapon.

Once you use this feature, you can’t use it again until you finish a long rest.

** Channel Divinity: Artisan's Blessing                              :lvl_2:
Starting at 2nd level, you can use your Channel Divinity to create simple items.

You conduct an hour-long ritual that crafts a nonmagical item that must include
some metal: a simple or martial weapon, a suit of armor, ten pieces of
ammunition, a set of tools, or another metal object. The creation is completed
at the end of the hour, coalescing in an unoccupied space of your choice on a
surface within 5 feet of you.

The thing you create can be something that is worth no more than 100 gp. As part
of this ritual, you must lay out metal, which can include coins, with a value
equal to the creation. The metal irretrievably coalesces and transforms into the
creation at the ritual’s end, magically forming even nonmetal parts of the
creation.

The ritual can create a duplicate of a nonmagical item that contains metal, such
as a key, if you possess the original during the ritual.

** Soul of the Forge                                   :lvl_6:resistance:ac:
Starting at 6th level, your mastery of the forge grants you special abilities:

You gain resistance to fire damage.
While wearing heavy armor, you gain a +1 bonus to AC.

** Divine Strike                                              :lvl_8:lvl_14:
At 8th level, you gain the ability to infuse your weapon strikes with the fiery
power of the forge. Once on each of your turns when you hit a creature with a
weapon attack, you can cause the attack to deal an extra 1d8 fire damage to the
target. When you reach 14th level, the extra damage increases to 2d8.

** Saint of Forge and Fire                                          :lvl_17:
At 17th level, your blessed affinity with fire and metal becomes more powerful:

- You gain immunity to fire damage.
- While wearing heavy armor, you have resistance to bludgeoning, piercing, and
  slashing damage from nonmagical attacks.

* Feats
** [[file:~/.emacs.d/ignore/org-dnd/16.feats.org::Squat Nimbleness][Squat Nimbleness]] 
| Type  | Value       |
|-------+-------------|
| ASI   | STR +1      |
| SKILL | Acrobatics  |
| ADV   | STR Grapple |

* Racial

