#+Latex_CLASS: dnd
#+STARTUP: content showstars indent
#+OPTIONS: tags:nil
#+TITLE: Bo Grimspine's Abilities
#+FILETAGS: bo grimspine abilities

* Class ([[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Cleric][Cleric]])                                                        :phb:
** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Channel Divinity][Channel Divinity]]                                     :lvl_2:lvl_6:lvl_18:
At 2nd level, you gain the ability to channel divine energy directly from your
deity, using that energy to fuel magical effects. You start with two such
effects: Turn Undead and an effect determined by your domain. Some domains grant
you additional effects as you advance in levels, as noted in the domain
description.

When you use your Channel Divinity, you choose which effect to create. You must
then finish a short or long rest to use your Channel Divinity again.

Some Channel Divinity effects require saving throws. When you use such an effect
from this class, the DC equals your cleric spell save DC.

Beginning at 6th level, you can use your Channel Divinity twice between rests,
and beginning at 18th level, you can use it three times between rests. When you
finish a short or long rest, you regain your expended uses.

|------+---+---|
| Left | 2 | 2 |
|------+---+---|

*** Channel Divinity: Turn Undead
As an action, you present your holy symbol and speak a prayer censuring the
undead. Each undead that can see or hear you within 30 feet of you must make a
Wisdom saving throw. If the creature fails its saving throw, it is turned for 1
minute or until it takes any damage.

A turned creature must spend its turns trying to move as far away from you as it
can, and it can't willingly move to a space within 30 feet of you. It also can't
take reactions. For its action, it can use only the Dash action or try to escape
from an effect that prevents it from moving. If there's nowhere to move, the
creature can use the Dodge action.

** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Harness Divine Power][Harness Divine Power]] (Optional)                      :lvl_2:lvl_6:lvl_18:
At 2nd level, you can expend a use of your Channel Divinity to fuel your spells.
As a bonus action, you touch your holy symbol, utter a prayer, and regain one
expended spell slot, the level of which can be no higher than half your
proficiency bonus (rounded up). The number of times you can use this feature is
based on the level you've reached in this class: 2nd level, once; 6th level,
twice; and 18th level, thrice. You regain all expended uses when you finish a
long rest.

** Ability Score Improvement              :lvl_4:lvl_8:lvl_12:lvl_16:lvl_19:
| Level | Type | Value            |
|-------+------+------------------|
|     4 | FEAT | Squat Nimbleness |
|     8 |      |                  |
|    12 |      |                  |
|    16 |      |                  |
|    19 |      |                  |

** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Cantrip Versatility][Cantrip Versatility (Optional)]]                                  :cantrip:
Whenever you reach a level in this class that grants the Ability Score
Improvement feature, you can replace one cantrip you learned from this class's
Spellcasting feature with another cantrip from the cleric spell list.

** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Destroy Undead][Destroy Undead]]                                                    :lvl_5:
Starting at 5th level, when an undead fails its saving throw against your Turn
Undead feature, the creature is instantly destroyed if its challenge rating is
at or below a certain threshold, as shown in the Cleric table above.

  | Cleric Level | Destroys Undead of CR |
  |--------------+-----------------------|
  | 5th          | 1/2 or lower          |
  
* Domain ([[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Forge Domain][Forge Domain]])                                                :xgte:

|--------------+------------------------------------------|
| Cleric Level | Spells                                   |
|--------------+------------------------------------------|
| 1st          | Identify, Searing Smite                  |
| 3rd          | Heat Metal, Magic Weapon                 |
| 5th          | Elemental Weapon, Protection from Energy |
| 7th          | Fabricated, Wall of Fire                 |
|--------------+------------------------------------------|

** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Bonus Proficiencies][Bonus Proficiencies]]                          :lvl_1:pb:heavy_armor:smith:
- Description ::
  Proficiency with heavy armor and smith's tools.

** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Blessing of the Forge][Blessing of the Forge]]                                             :lvl_1:
- Description ::
  End of long rest make an object (armor, shield, or weapon) +1.
  Its now magical. Feature can only be used 1 time per long rest.

  |----------+----------|
  | Added To | Armor +1 |
  |----------+----------|

** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Channel Divinity: Artisan's Blessing][Channel Divinity: Artisan's Blessing]]                              :lvl_2:
- Description ::
  Cast time: 1 hour ritual
  Components: Material to create object (must have metal in it)
  Creates: Simple or martial weapon, armor, 10 of an ammunition, ETC.

  Can duplicate of non-magical object. The object has to be present. EX a key.
  
* Feats
** [[file:~/.emacs.d/ignore/org-dnd/16.feats.org::Squat Nimbleness][Squat Nimbleness]] 
| Type  | Value       |
|-------+-------------|
| ASI   | STR +1      |
| SKILL | Acrobatics  |
| ADV   | STR Grapple |

* Racial

