#+LATEX_CLASS: dnd
#+STARTUP: content showstars indent
#+OPTIONS: tags:nil
#+TITLE: Bo Grimespine's Background Sheet
#+FILETAGS: baddah bing background sheet

* Soldier                        :background:athletics:intimidation:vehicles:
War has been your life for as long as you care to remember. You trained as a
youth, studied the use of weapons and armor, learned basic survival techniques,
including how to stay alive on the battlefield. You might have been part of a
standing national army or a mercenary company, or perhaps a member of a local
militia who rose to prominence during a recent war.

When you choose this background, work with your DM to determine which military
organization you were a part of, how far through its ranks you progressed, and
what kind of experiences you had during your military career. Was it a standing
army, a town guard, or a village militia? Or it might have been a noble’s or
merchant’s private army, or a mercenary company.

Skill Proficiencies: Athletics, Intimidation
Tool Proficiencies: One type of gaming set, vehicles (land)
Equipment: An insignia of rank, a trophy taken from a fallen enemy (a dagger,
broken blade, or piece of a banner), a set of bone dice or deck of cards,
a set of common clothes, and a pouch containing 10 gp

** Feature: Military Rank
You have a military rank from your career as a soldier. Soldiers loyal to your
former military organization still recognize your authority and influence, and
they defer to you if they are of a lower rank. You can invoke your rank to exert
influence over other soldiers and requisition simple equipment or horses for
temporary use. You can also usually gain access to friendly military encampments
and fortresses where your rank is recognized.

* Favorite Scheme
5 - I put on new identities like clothes

Feature: False Identity
You have created a second identity that includes documentation, established
acquaintances, and disguises that allow you to assume that persona.
Additionally, you can forge documents including official papers and personal
letters, as long as you have seen an example of the kind of document or the
handwriting you are trying to copy.

* Personality Trait
I have a crude sense of humor.
I can stare down a hell hound without flinching

* Ideal
Responsibility. I do what i must and obey just authority. (Lawful)

* Bond
My honor is my life.

* Flaw
I made a terrible mistake in battle that cost many lives -- and I would do
anything to keep that mistake secret

* Alignment
Lawful Neutral

* Faith

* Lifestyle
Modest

* Physical Characteristics
** Hair
Gray

** Skin
Tan

** Eyes
Green

** Height
4"3'

** Weight
187

** Age (Years)
95

** Gender
Male
