#+LATEX_CLASS: dnd
#+STARTUP: content showstars indent
#+OPTIONS: tags:nil
#+TITLE: Bo Grimspine's Spells
#+FILETAGS: bo grimespine spells

* Cantrips

** Spare the Dying                                             :phb:cantrip:
Necromancy cantrip

Casting Time: 1 action
Range: Touch
Components: V, S
Duration: Instantaneous

You touch a living creature that has 0 hit points. The creature becomes stable.
This spell has no effect on undead or constructs.   

** Toll the Dead                             :xanathars_guide_to_everything:
Necromancy cantrip

Casting Time: 1 action
Range: 60 feet
Components: V, S
Duration: Instantaneous

You point at one creature you can see within range, and the sound of a dolorous bell fills the air around it for a moment. The target must succeed on a Wisdom saving throw or take 1d8 necrotic damage. If the target is missing any of its hit points, it instead takes 1d12 necrotic damage.

At Higher Levels. The spell’s damage increases by one die when you reach 5th level (2d8 or 2d12), 11th level (3d8 or 3d12), and 17th level (4d8 or 4d12).
