#+STARTUP: content showstars indent
#+FILETAGS: dnd background Chewy Eshieldoor

* Outlander 
** Description
You grew up in the wilds, far from civilization and the comforts of town and technology.
You’ve witnessed the migration of herds larger than forests, survived weather more extreme
than any city-dweller could comprehend, and enjoyed the solitude of being the only thinking
creature for miles in any direction. The wilds are in your blood, whether you were a nomad,
an explorer, a recluse, a hunter-gatherer, or even a marauder. Even in places where you don’t
know the specific features of the terrain, you know the ways of the wild.

** Bonus
*Skill Proficiencies*: Athletics, Survival
*Tool Proficiencies*: One type of musical instrument
*Languages*: One of your choice
*Equipment*:
A staff,
a hunting trap,
a trophy from an animal you killed,
a set of traveler’s clothes,
and a pouch containing 10 gp

** Wanderer :feature:
You have an excellent memory for maps and geography, and you can always recall the
general layout of terrain, settlements, and other features around you. In addition,
you can find food and fresh water for yourself and up to five other people each day,
provided that the land offers berries, small game, water, and so forth.

* Personality Trait
I watch over my friends as if they were a litter of newborn pups.
have an excellent memory for maps and geography, and you can always recall the
general layout of terrain, settlements, and other features around you. In addition,
you can find food and fresh water for yourself and up to five other people each day,
provided that the land offers berries, small game, water, and so forth.
* Ideal
Glory. I must earn glory in battle, for myself and my clan. (Any)

* Bond
My family, clan, or tribe is the most important thing in my life, even when they are far from me.

* Flaw
I am slow to trust members of other races, tribes, and societies.

* Goliath
Ability Score Increase
Your Strength score increases by 2, and your Constitution score increases by 1.

Age
Goliaths have lifespans comparable to humans. They enter adulthood in their late teens and usually live less than a century.

Size
Goliaths are between 7 and 8 feet tall and weigh between 280 and 340 pounds. Your size is Medium.

Speed
Your base walking speed is 30 feet.

Natural Athlete
You have proficiency in the Athletics skill.

Stone’s Endurance
You can focus yourself to occasionally shrug off injury. When you take damage, you can use your reaction to roll a d12. Add your Constitution modifier to the number rolled and reduce the damage by that total. After you use this trait, you can’t use it again until you finish a short or long rest.

Powerful Build
You count as one size larger when determining your carrying capacity and the weight you can push, drag, or lift.

Mountain Born
You have resistance to cold damage. You’re also acclimated to high altitude, including elevations above 20,000 feet.

Languages
You can speak, read, and write Common and Giant.
