#+TILE: Baddah Boom - Features

* Racial
** Stone’s Endurance
   You can focus yourself to occasionally shrug off injury. When you take damage,
   you can use your reaction to roll a d12. Add your Constitution modifier to the
   number rolled and reduce the damage by that total. After you use this trait, you
   can’t use it again until you finish a short or long rest.

** Powerful Build
   You count as one size larger when determining your carrying capacity and the weight you can push, drag, or lift.

** Mountain Born
   You have resistance to cold damage. You’re also acclimated to high altitude, including elevations above 20,000 feet.

* Class
     T h e B a r b a r i a n
Level
Proficiency
Bonus Features Rages
Rage
Damage
1st +2 Rage, Unarmored
Defense
2 +2
2nd +2 Reckless Attack,
Danger Sense
2 +2
3rd +2 Primal Path 3 +2
4th +2 Ability Score
Improvement
3 +2
5th +3 Extra Attack,
Fast Movement
3 +2
6th +3 Path feature 4 +2
7th +3 Feral Instinct 4 +2
8th +3 Ability Score
Improvement
4 +2
9th +4 Brutal Critical
(1 die)
4 +3
10th +4 Path feature 4 +3
11th +4 Relentless Rage 4 +3
12th +4 Ability Score
Improvement
5 +3
13th +5 Brutal Critical
(2 dice)
5 +3
14th +5 Path feature 5 +3
15th +5 Persistent Rage 5 +3
16th +5 Ability Score
Improvement
5 +4
17th +6 Brutal Critical
(3 dice)
6 +4
18th +6 Indomitable
Might
6 +4
19th +6 Ability Score
Improvement
6 +4
20th +6 Primal Champion Unlimited +4

* Background
