#+TILE: Baddah Boom - Features

* Racial
  - Darkvision ::
    Accustomed to life underground, you have superior vision in dark and dim conditions. You can see in dim light
    within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can't discern color
    in darkness, only shades of gray.
     
  - Gnome Cunning ::
    You have advantage on all Intelligence, Wisdom, and Charisma saving throws against magic.

  - Artificier's Lore ::
    Whenever you make an Intelligence (History) check related to magic items, alchemical objects, or technological
    devices, you can add twice your proficiency bonus, instead of any proficiency bonus you normally apply.

  - Tinker ::
    You have proficiency with artisan's tools (tinker's tools). Using those tools, you can spend 1 hour and 10 gp worth
    of materials to construct a Tiny clockwork device (AC 5, 1 hp). The device ceases to function after 24 hours
    (unless you spend 1 hour repairing it to keep the device functioning), or when you use your action to dismantle it;
    at that time, you can reclaim the materials used to create it. You can have up to three such devices active at a
    time.

    When you create a device, choose one of the following options:
     
    - Clockwork Toy ::
      This toy is a clockwork animal, monster, or person, such as a frog, mouse, bird, dragon, or soldier. When placed
      on the ground, the toy moves 5 feet across the ground on each of your turns in a random direction. It makes
      noises as appropriate to the creature it represents.

    - Fire Starter ::
      The device produces a miniature flame, which you can use to light a candle, torch, or campfire. Using the device
      requires your action.

    - Music Box ::
      When opened, this music box plays a single song at a moderate volume. The box stops playing when it reaches the
      song's end or when it is closed.
     
* Class
  - Magical Tinkering ::
    You've learned how to invest a spark of magic into
    mundane objects. To use this ability, you must have
    thieves' tools or artisan's tools in hand. You then
    touch a Tiny nonmagical object as an action and
    give it one of the following magical properties of
    your choice:
     
    - The object sheds bright light in a 5-foot radius and
      dim light for an additional 5 feet.
       
    - Whenever tapped by a creature, the object emits a
      recorded message that can be heard up to 10 feet
      away. You utter the message when you bestow this
      property on the object, and the recording can be
      no more than 6 seconds long.
       
    - The object continuously emits your choice of an
      odor or a nonverbal sound (wind, waves, chirping,
      or the like). The chosen phenomenon is perceivable up to 10 feet away.
       
    - A static visual effect appears on one of the object's
      surfaces. This effect can be a picture, up to 25
      words of text, lines and shapes, or a mixture of
      these elements, as you like.
       
    The chosen property lasts indefinitely. As an
    action, you can touch the object and end the property early.

    You can bestow magic on multiple objects,
    touching one object each time you use this feature,
    though a single object can only bear one property
    at a time. The maximum number of objects you
    can affect with this feature at one time is equal to
    your Intelligence modifier (minimum of one object). If you try to exceed your maximum, the oldest
    property immediately ends, and then the new property applies.

  - Infuse Item ::
    You've gained the ability to imbue mundane items with certain magical infusions, turning those objects into magic
    items.
     
    - Infusions Known ::
      When you gain this feature, pick four artificer infusions to learn, choosing from the "Artificer Infusions"
      section at the end of the class's description. You learn additional infusions of your choice when you reach
      certain levels in this class, as shown in the Infusions Known column of the Artificer table.
 
      Whenever you gain a level in this class, you can replace one of the artificer infusions you learned with a new one.
       
    - Infusing an Item ::
      Whenever you finish a long rest, you can touch a nonmagical object and imbue it with one of your artificer
      infusions, turning it into a magic item. An infusion works on only certain kinds of objects, as specified in the
      infusion's description. If the item requires attunement, you can attune yourself to it the instant you infuse the
      item. If you decide to attune to the item later, you must do so using the normal process for attunement (see the
      attunement rules in the Dungeon Master's Guide). 
 
      Your infusion remains in an item indefinitely, but when you die, the infusion vanishes after a number of days
      equal to your Intelligence modifier (minimum of 1 day). The infusion also vanishes if you replace your knowledge
      of the infusion.
 
      You can infusemore than one nonmagical object at the end of a long rest; the maximum number of objects appears in
      the Infused Items column of the Artificer table. You must touch each of the objects, and each of your infusions
      can be in only one object at a time. Moreover, no object can bear more than one of your infusions at a time. If
      you try to exceed your maximum number of infusions, the oldest infusion ends, and then the new infusion applies.
 
      If an infusion ends on an item that contains other things, like a bag of holding, its contents harmlessly appear
      in and around its space.
 
    - Infusions
      - Enhanced Defense (Splint Armor) ::
        A creature gains a +1 bonus to Armor Class while wearing (armor) or wielding (shield) the infused item. The
        bonus increases to +2 when you reach 10th level in this class.
 
      - Homunculus Servant ::
        You learn intricate methods for magically creating a special homunculus that serves you. The item you infuse
        serves as the creature's heart, around which the creature's body instantly forms. You determine the homunculus's
        appearance. Some artificers prefer mechanical-looking birds, whereas some like winged vials or miniature,
        animate cauldrons.
 
        The homunculus is friendly to you and your companions, and it obeys your commands. See this creature's game
        statistics in the [[file:npcs/homunculus-servant.org][Homunculus Servant]] stat block, which uses your proficiency bonus (PB) in several places.
 
        In combat, the homunculus shares your initiative count, but it takes its turn immediately after yours. It can
        move and use its reaction on its own, but the only action it takes on its turn is the Dodge action, unless you
        take a bonus action on your turn to command it to take another action. That action can be one in its stat block
        or some other action. If you are incapacitated, the homunculus can take any action of its choice, not just Dodge.
 
        The homunculus regains 2d6 hit points if the mending spell is cast on it. If you or the homunculus dies, it
        vanishes. leaving its heart in its space.
         
  - Artificier Specialist (Armorer) ::
    Choose the type of specialist you are: Alchemsit, Armorer, Artillerist, or Battle Smith, each of which is detailed
    after the class's description. Your choice grants you features at 5th level and again at 9th and 15th level.

  - Right Tool For The Job ::
    You've learned how to produce exactly the tool you need: with thieves' tools or artisan's tools in hand,
    you can magically create one set of artisan's tools in an unoccupied space within 5 feet of you. This creation
    requires 1 hour of uninterrupted work, which can coincide with a short or long rest. Though the product of magic,
    the tools are nonmagical, and they vanish when you use this feature again.

  - Tools of the Trade ::
    You gain proficiency with heavy armor. You also
    gain proficiency with smith's tools. If you already
    have this tool proficiency, you gain proficiency with
    one other type of artisan's tools of your choice.

  - Arcane Armor ::
    Your metallurgical pursuits have led to you making armor a conduit for your magic. As an action, you can turn a suit
    of armor you are wearing into Arcane Armor, provided you have smith's tools in hand. You gain the following benefits
    while wearing this armor:
    
    - If the armor normally has a Strength requirement, the arcane armor lacks this requirement for you.
       
    - You can use the arcane armor as a spellcasting focus for your artificer spells.
       
    - The armor attaches to you and can't be removed against your will. It also expands to cover your entire body,
      although you can retract or deploy the helmet as a bonus action. The armor replaces any missing limbs, functioning
      identically to a limb it replaces.
       
    - You can doff or don the armor as an action. The armor continues to be Arcane Armor until you don another suit of
      armor or you die.

  - Armor Model ::
    You can customize your Arcane Armor. When you do so, choose one of the following armor models: Guardian or
    Infiltrator. The model you choose gives you special benefits while you wear it.
 
    Each model includes a special weapon. When you attack with that weapon, you can add your Intelligence modifier,
    instead of Strength or Dexterity, to the attack and damage rolls.
 
    You can change the armor's model whenever you finish a short or long rest, provided you have smith's tools in hand.
 
    - Guardian ::
      You design your armor to be in the front line of conflict. It has the following features:
       
      - Thunder Gauntlets ::
        Each of the armor's gauntlets counts as a simple melee weapon while you aren't holding anything in it, and it
        deals ld8 thunder damage on a hit. A creature hit by the gauntlet has disadvantage on attack rolls against
        targets other than you until the start of your next turn, as the armor magically emits a distracting pulse when
        the creature attacks someone else.
         
      - Defensive Field :: As a bonus action, you can gain temporary hit points equal to your level in this class,
        replacing any temporary hit points you already have. You lose these temporary hit points if you doff the armor.
        You can use this bonus action a number of times equal to your proficiency bonus, and you regain all expended
        uses when you finish a long rest.
        
    - Infiltrator ::
      You customize your armor for subtle undertakings. It has the following features:
 
      - Lightning Launcher ::
        A gemlike node appears on one of your armored fists or on the chest (your choice). It counts as a simple ranged
        weapon, with a normal range of 90 feet and a long range of 300 feet, and it deals ld6 lightning damage on a hit.
        Once on each of your turns when you hit a creature with it, you can deal an extra ld6 lightning damage to that
        target.
         
      - Powered Steps ::
        Your walking speed increases by 5 feet.
 
      - Dampening Field ::
        You have advantage on Dexterity (Stealth) checks. If the armor normally imposes disadvantage on such checks, the
        advantage and disadvantage cancel each other, as normal.
     
* Background
  - False Identity ::
    You have created a second identity that includes documentation, established acquaintances, and disguises that allow
    you to assume that persona. Additionally, you can forge documents including official papers and personal letters,
    as long as you have seen an example of the kind of document or the handwriting you are trying to copy.
