 #+STARTUP: content showstars indent
#+FILETAGS: dnd notes indi jones dr
* Mid Port
There are 3 layers, slums, middle class, and nobility
Going to stay in the slums and we have a show at the middle class in.
/Entered on/ [2022-04-29 Fri 19:47]
* The wealthiest family are gnomes
/Entered on/ [2022-04-29 Fri 19:50]
* At the tavern Klepto, trixie, lola
/Entered on/ [2022-04-29 Fri 19:52]
* Approached by leven sackauser WORKS AT A RESTAURANT - The fraggle family sligbus
Light blue crystal was stolen and inside there is a squid
/Entered on/ [2022-04-29 Fri 19:55]
* They hold weekly events for nobles. 
/Entered on/ [2022-04-29 Fri 20:00]
* The guards travel in patrol units around 5 people per group a couple shields and one leaders
Guards are larger races alot of the nobility are gnomes
/Entered on/ [2022-04-29 Fri 20:28]


* Met with Goober, Atlas, Kimar, Snig, DunkinShiek, Silvy

Make our way to the afterlife casino to steal a statuet and some money based items
We will meet verity and tazier at the casino. One of the reasons this money is
important is because it is important to the golden vault industry.

We made it to tazier and we make our way to the brinewidow. We meet verity kai
and she talks about a secret. Quieten togglepocket stole the money of verity.
He used this money to open the seven hells casino. We are to steal the winged
statue and 5000 gold pieces. She pulls out a purple and red stitching out
to hold all of the gold. (Bag of holding).

We make it to the casino after being fairied into the casino. Once inside we go
to the spa to get a massage and a bath.

/Entered on/ [2023-03-26 Sun 18:13]

