#+LATEX_CLASS: dnd
#+STARTUP: content showstars indent
#+OPTIONS: tags:nil
#+TITLE: Tenzor's Abilities
#+FILETAGS: tenzor abilities

* Abilities  
** Class
*** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Bardic Inspiration][Bardic Inspiration]] (1/1)                    :lvl_1:lvl_5:lvl_10:lvl_15:

- Time :: 10 minutes
- Range :: 60ft on one other creature not yourself.
- Dice :: 1d6
- Uses :: CHA MOD or minimum 1
- Regain :: Long rest (all expended)
  
Add dice to one ability check, attack roll, or saving throw.
The creature can wait until after it rolls the d20 before
deciding to use the Bardic Inspiration die, but must decide before the
GM says whether the roll succeeds or fails.

One Bardic Inspiration die at a time per creature.

*** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::Jack of All Trades][Jack of All Trades]]                                              :lvl_2:
Add 1/2 proficiency bonus on skill checks that do not already include it.

*** [[file:~/.emacs.d/ignore/org-dnd/02.classes.org::*Song of Rest][Song of Rest]]                                                    :lvl_2:
Short rest, gain 1d6 extra health if you or an allied creature expend 1 or more
hit dice.

** Background
*** [[file:~/.emacs.d/ignore/org-dnd/04.personalization.org::False Identity][False Identity]]
You have created a second identity that includes documentation, established
acquaintances, and disguises that allow you to assume that persona. Additionally,
you can forge documents including official papers and personal letters, as long
as you have seen an example of the kind of document or the handwriting you are
trying to copy.

** Racial
*** Shape-changer
As an action, you can change your appearance and your voice. You determine
the specifics of the changes, including your coloration, hair length, and
sex. You can also adjust your height and weight, but not so much that your
size changes. You can make yourself appear as a member of another race,
though none of your game statistics change. You can’t duplicate the
appearance of a creature you’ve never seen, and you must adopt a form that
has the same basic arrangement of limbs that you have. Your clothing and
equipment aren’t changed by this trait.

You stay in the new form until you use an action to revert to your true form
or until you die.


