#+LATEX_CLASS: dnd
#+STARTUP: content showstars indent
#+OPTIONS: tags:nil
#+TITLE: Tenzor's Spells
#+FILETAGS: tenzor spells

* Cantrips
** [[file:~/.emacs.d/ignore/org-dnd/10.spells.org::*Mage Hand][Mage Hand]]
- Casting Time :: 1 action
- Range :: 30 feet
- Components :: V, S
- Duration :: 1 minute

A spectral, floating hand appears at a point you choose within range. The hand
lasts for the duration or until you dismiss it as an action. The hand vanishes
if it is ever more than 30 feet away from you or if you cast this spell again.

You can use your action to control the hand. You can use the hand to manipulate
an object, open an unlocked door or container, stow or retrieve an item from an
open container, or pour the contents out of a vial. You can move the hand up
to 30 feet each time you use it.

The hand can't attack, activate magic items, or carry more than 10 pounds.

** [[file:~/.emacs.d/ignore/org-dnd/10.spells.org::*Vicious Mockery][Vicious Mockery]]
- Casting Time :: 1 action
- Range :: 60 feet
- Components :: V
- Duration :: Instantaneous

Damage 1d4 + disadvantage on next attack roll before the end of its next turn.
WIS saving throw

* Level 1 (4/4)
** [[file:~/.emacs.d/ignore/org-dnd/10.spells.org::*Dissonant Whispers][Dissonant Whispers]]
- Casting Time :: 1 action
- Range :: 60 feet
- Components :: V
- Duration :: Instantaneous

Damage: 3d6

WIS saving throw.

On save: 1/2 damage
- Deaf creatures automatically save.

On fail: damage + uses reaction to move away from caster

- At Higher Levels ::
  When you cast this spell using a spell slot of 2nd level or higher, the damage
  increases by 1d6 for each slot level above 1st.
  
** [[file:~/.emacs.d/ignore/org-dnd/10.spells.org::*Healing Word][Healing Word]]
- Casting Time :: 1 bonus action
- Range :: 60 feet
- Components :: V
- Duration :: Instantaneous

A creature of your choice that you can see within range regains hit points equal
to 1d4 + your spellcasting ability modifier. This spell has no effect on undead
or constructs.

- At Higher Levels :: 
  When you cast this spell using a spell slot of 2nd level or higher, the healing
  increases by 1d4 for each slot level above 1st.
  
** [[file:~/.emacs.d/ignore/org-dnd/10.spells.org::Sleep][Sleep]]
- Casting Time :: 1 action
- Range :: 90 feet
- Components :: V, S, M (a pinch of fine sand, rose petals, or a cricket)
- Duration :: 1 minute

This spell sends creatures into a magical slumber. Roll 5d8, the total is how
many hit points of creatures this spell can affect. Creatures within 20 feet of
a point you choose within range are affected in ascending order of their current
hit points (ignoring unconscious creatures).

Starting with the creature that has the lowest current hit points, each creature
affected by this spell falls unconscious until the spell ends, the sleeper takes
damage, or someone uses an action to shake or slap the sleeper awake. Subtract
each creature’s hit points from the total before moving on to the creature with
the next lowest hit points. A creature’s hit points must be equal to or less
than the remaining total for that creature to be affected. Undead and creatures
immune to being charmed aren’t affected by this spell.

- At Higher Levels ::
  When you cast this spell using a spell slot of 2nd level or higher, roll an
  additional 2d8 for each slot level above 1st.
  
** [[file:~/.emacs.d/ignore/org-dnd/10.spells.org::*Thunderwave][Thunderwave]]
- Casting Time :: 1 action
- Range :: Self (15-foot cube)
- Components :: V, S
- Duration :: Instantaneous

A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube
originating from you must make a Constitution saving throw. On a failed save, a
creature takes 2d8 thunder damage and is pushed 10 feet away from you. On a
successful save, the creature takes half as much damage and isn't pushed.

In addition, unsecured objects that are completely within the area of effect are
automatically pushed 10 feet away from you by the spell's effect, and the spell
emits a thunderous boom audible out to 300 feet.

- At Higher Levels ::
  When you cast this spell using a spell slot of 2nd level or higher, the damage
  increases by 1d8 for each slot level above 1st.
