#+STARTUP: content showstars indent
#+FILETAGS: dnd notes baddah_boom
* Note                                        :eveland:tribor:giant:
Grabbed 10 suits of scraped armor in triboar
   
We own an ax beak that we ride.
   
kaitlyn sarser the bar keep.
   Investing in the theater for this. 1000 gp.
   Writing a contract. - written and we have 2 a week shows about iron fist, 10% of sales, and 50% of tonic sales.
The lord protector(darthra) - sending us to Everland we are being sent to Danavar

eveland we sold 10 scraps of armor to a dwarf named tark.

krowen valharroh after drinking wine.
the feyrun, concerned that giants are being more aggressive.
Agents sent but didnt make it.

Kryshilir the stone giant. their god laid out heirarchy and its broken.
Hotun-shul (place) knowledge broken hierarchy. 

/Entered on/ [2022-02-20 Sun 14:51]
* Note                                        :giant:hotunshul:

The ordining hierarchy has been broken. The god of the giants anom the all father has broken it. They are trying to re-align it.


/Entered on/ [2022-02-20 Sun 17:43]
* Playing with Belbis, Seph, Raygan, Beary, and boom
/Entered on/ [2022-02-20 Sun 18:43]
* Esme and Erma
They are splinter twin of the Leinore, the Autmn Sovereign.
/Entered on/ [2022-11-12 Sat 21:45]
